### ISSUE TITLE
Unable to change the flow from horizontal scrolling to vertical scrolling from react native

### ISSUE THREAD

**Issue by SamuelPremji** [victorsoares96/epubjs-react-native#104]
I can change the flow by adding it here in the files of the library, precisely the template.ts file but I cannot change the flow conditionally straight from react native. I want there to be a button but in my expo react native code that allows me to change the flow when pressed.

rendition = book.renderTo("viewer", {
        width: "100%",
        height: "100%",
        spread: 'none',
        manager: "continuous",
        flow: 'scrolled',
      });

**Comment by Mujab01** [comment]
@SamuelPremji  Could you please exactly define where you made these changes. I want to make to it scrollable

**Comment by Mujab01** [comment]
> I can change the flow by adding it here in the files of the library, precisely the template.ts file but I cannot change the flow conditionally straight from react native. I want there to be a button but in my expo react native code that allows me to change the flow when pressed.
> 
> rendition = book.renderTo("viewer", { width: "100%", height: "100%", spread: 'none', manager: "continuous", flow: 'scrolled', });

@SamuelPremji I Tried this but not working for me .Any help??
