### ISSUE TITLE
Any way to extract the text from the epub?

### ISSUE THREAD

**Issue by SKJones90** [victorsoares96/epubjs-react-native#106]
I am looking for a way to extract the text from the epub file instead of simply displaying the file to the user. Is it possible with this project?

**Comment by alexjyong** [comment]
I haven't tried this in the plugin, only with stock epub.js (which this is based on), but this seems to work when using epub.js with web browser javascript.

```
// Initialize the book with the path to the .epub file
var book = ePub("myEpub.epub");

// Array to store the text contents of each section
var sectionsContents = [];

// Render the book
var rendition = book.renderTo("area", {  flow: "scrolled-doc", width: 600, height: 400 }); //area points to an id of an element on the web page

// Handle rendering events
rendition.display().then(async function() {
  var spineItems = rendition.book.spine.spineItems;
  console.log(spineItems.length)
  for(var i =0; i< spineItems.length; i++){
    spineItem = spineItems[i];
    sectionsContents.push(spineItem.contents.innerText);
    await rendition.next()
  }
    
});
```

It's a bit clunky, you have to render each section before hand, but it does the job.

if you could access the epub libraries somehow in the plugin, maybe use a webview(?), this could get you started.

**Comment by rashidwiizb** [comment]
how can i do this on mobile app to get the each element or text with cfi ranges from each page of epub?

**Comment by victorsoares96** [comment]
> I haven't tried this in the plugin, only with stock epub.js (which this is based on), but this seems to work when using epub.js with web browser javascript.
> 
> ```
> // Initialize the book with the path to the .epub file
> var book = ePub("myEpub.epub");
> 
> // Array to store the text contents of each section
> var sectionsContents = [];
> 
> // Render the book
> var rendition = book.renderTo("area", {  flow: "scrolled-doc", width: 600, height: 400 }); //area points to an id of an element on the web page
> 
> // Handle rendering events
> rendition.display().then(async function() {
>   var spineItems = rendition.book.spine.spineItems;
>   console.log(spineItems.length)
>   for(var i =0; i< spineItems.length; i++){
>     spineItem = spineItems[i];
>     sectionsContents.push(spineItem.contents.innerText);
>     await rendition.next()
>   }
>     
> });
> ```
> 
> It's a bit clunky, you have to render each section before hand, but it does the job.
> 
> if you could access the epub libraries somehow in the plugin, maybe use a webview(?), this could get you started.

You can use the new functionality from version 1.4.0 applied in the JavaScript Injection example in the examples folder
