### ISSUE TITLE
Links inside epubs are not working

### ISSUE THREAD

**Issue by natesanyo** [victorsoares96/epubjs-react-native#11]

**Comment by jknvlvxs** [comment]
I'm having the same issue. Links and summary itens that should navigate to some location of epub aren't working

**Comment by natesanyo** [comment]
I have come up with a solution that works for me but I'm not sure it's clean enough for a pull request. I just make these two changes to the epubjs-react-native/src/Reader.tsx file. Both of these changes are **<WebView> properties**: 

1. Enable internal linking in Android. Adding a baseUrl works for Android because it gives epubjs in the enclosed WebView a self-referencing context to base its navigation off of. 
Remove this line: 
-                source={{ html: template }}
Add this line: 
+                source={{ html: template, baseUrl: "file://" }}

2. Enable internal linking in iOs. Adding this onShouldStartLoadWithRequest works because it captures the navigation event before it is attempted and then uses the goToLocation hook to make the location change. 
Add these lines: 
+                onShouldStartLoadWithRequest={(request)=>{
+                  if(!isLoading && request.url != request.mainDocumentURL) {
+                    goToLocation(request.url.replace(request.mainDocumentURL, ""))
+                  }
+                  return true;
+                }}

Let me know if you need a copy of the Reader.tsx file.

**Comment by jknvlvxs** [comment]
Thanks man, it worked for me. I updated in my project using patch-package, but I think you shoud make a pull request to fix this issue. 🤗

**Comment by natesanyo** [comment]
Great. Thanks for the encouragement. I opened a pull request. Nate
www.chapellibrary.org

**Comment by victorsoares96** [comment]
thanks @natesanyo i'll see your opened pr and i'll be including this improvement in the next version 🎉

**Comment by afrazs** [comment]
Along with that, I have noticed that it looks into OEBPS/file.xhtml directory. So I have made it to file.xhtml only and it works for me.

`goToLocation(
                      request.url.replace(request.mainDocumentURL, '').split('/')[1]
                      //for ePub, it actually looks into directory OEBPS/file.xhtml. Making it to file.xhtml only
                    );`
