### ISSUE TITLE
Highlight selected text?

### ISSUE THREAD

**Issue by Sreedevi-sps** [victorsoares96/epubjs-react-native#110]
How can we highlight selected text in our customised colour? Right now we only have options for share, copy and translate.

**Comment by SamuelPremji** [comment]
> How can we highlight selected text in our customised colour? Right now we only have options for share, copy and translate.

Did you figure out a way to have more options than share, copy and translate?

**Comment by Sreedevi-sps** [comment]
> > How can we highlight selected text in our customised colour? Right now we only have options for share, copy and translate.
> 
> Did you figure out a way to have more options than share, copy and translate?

Yes. Figure out way for customising menu. I added custom option for highlight and copy. But how can we add the functionality for same? As of now, selected text is highlighted at that instance. But in my case, I want to highlight only when that particular option is selected from custom menu.

**Comment by victorsoares96** [comment]
@Sreedevi-sps I added a new annotation API that could help you with your problem, take a look at this related pull request!
