### ISSUE TITLE
onSelected not working (iOS 16, device, Expo Go)

### ISSUE THREAD

**Issue by dukuo** [victorsoares96/epubjs-react-native#111]
Hi, i'm trying to run this code at there's no console.log of the selected text:

```
import * as React from 'react'

import { SafeAreaView, useWindowDimensions } from 'react-native'
import { Reader, ReaderProvider } from '@epubjs-react-native/core'
// import { useFileSystem } from '@epubjs-react-native/file-system'; // for Bare React Native project
import { useFileSystem } from '@epubjs-react-native/expo-file-system' // for Expo project

export function BookScreen() {
  const onSelected = (selectedText, cfiRange) => console.log(selectedText)
  const { width, height } = useWindowDimensions()
  return (
    <SafeAreaView>
      <ReaderProvider>
        <Reader
          src="https://s3.amazonaws.com/moby-dick/OPS/package.opf"
          width={width}
          height={height}
          fileSystem={useFileSystem}
          onSelected={(selected, cfiRange) => console.log(selected, cfiRange)}
        />
      </ReaderProvider>
    </SafeAreaView>
  )
}

```

Am I doing something wrong?

Thank you!

**Comment by leonardonegrao** [comment]
I had the same issue, and from what I found out, it seems like an issue with scripted content.

Basically, this library uses React Native's `WebView` to render HTML code, and by injecting the `epubjs` library, it renders the book, and enables everything else.

If you look at [line 52 of template.ts](https://github.com/victorsoares96/epubjs-react-native/blob/71af748c768b4fd6b98040efb45ad6cdf9276c22/src/template.ts#L52), that's when the book is rendered to the desired `div`. The `epubjs` library handles that part, by creating an iFrame inside the `div`.

When I tried pressing on the iFrame, the `WebView` console showed an error (you can check by using Safari's development tools):

```
Blocked script execution in 'about:srcdoc' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

[I found this issue](https://github.com/react-native-webview/react-native-webview/issues/2350) on the react-native-webview repo, of somebody using `epubjs` and having the same problem.

So I believe the solution is, as explained in the `epubjs` docs, to add the `allowScriptedContent: true` line.

@victorsoares96 you might have more context about this

**Comment by victorsoares96** [comment]
@leonardonegrao, I read about this problem and I think the only way is to apply this solution, the `allowScriptedContent` parameter will be **true** by default only on **iOS**

**Comment by victorsoares96** [comment]
Guys, I fixed this problem in the pull request mentioned, I'm closing this issue if anyone continues to have this problem, please report
