### ISSUE TITLE
loading stuck at 0%

### ISSUE THREAD

**Issue by vishal27shenoy** [victorsoares96/epubjs-react-native#113]

**Comment by Natnael-Guchima** [comment]
I am having the same issue when installing the package, and running it.

**Comment by Natnael-Guchima** [comment]
a gentle bumpe @victorsoares96

**Comment by Natnael-Guchima** [comment]
@vishal27shenoy have you been able to solve the issue?

**Comment by Desintegrator** [comment]
any updates?

**Comment by vishal27shenoy** [comment]
If anyone is still facing issues, try the following steps:

1. Delete the "node_modules" folder.
2. Remove the "@epubjs-react-native/core" package from your dependencies.
3. Run `npm install` to reinstall dependencies.
4. Install version 1.1.0 of the "@epubjs-react-native/core" package using the command `npm i @epubjs-react-native/core@1.1.0`.
