### ISSUE TITLE
Dependency issue with bare installation

### ISSUE THREAD

**Issue by TirumalReddy** [victorsoares96/epubjs-react-native#116]
When installing on react native app , I got dependency issue. Please refer below image

<img width="422" alt="epubjs_react-native_issue" src="https://github.com/victorsoares96/epubjs-react-native/assets/40593164/4074966e-5652-4323-986a-a2453f752e2e">

**Comment by Anton-Kravkenko** [comment]
Reset the expo shell

**Comment by TirumalReddy** [comment]
Issue in react native cli mode app not expo app, I am getting expo-file-system not found error in react-native cli app

**Comment by ekjkkk153** [comment]
It happens to me too.
I'm not gonna use expo and it has supported for bare project until 1.2.0, but after 1.3.0 the expo-file-system dependency was added, it forces me to change or rebuild my bare project into expo-based project.

It seems that the code was added on #107 to fix #57 to serve jszip & epubjs locally.
I think the code for serving jszip & epubjs should use FileSystem on @epubjs-react-native/file-system or @epubjs-react-native/expo-file-system, not expo-file-system directly.

**Comment by victorsoares96** [comment]
Hi guys, I'm already working on a solution for this and it should be out in the next few days! Sorry for the delay
