### ISSUE TITLE
Navigation between pages.

### ISSUE THREAD

**Issue by janstevcik21** [victorsoares96/epubjs-react-native#122]
Is there possibility to get locations of pages that are rendered one by one and navigate in pages using slider?

**Comment by victorsoares96** [comment]
Do you say something like this?
![image](https://github.com/victorsoares96/epubjs-react-native/assets/19741953/91d3e8e8-0015-47fd-83bf-4acda1118fe8)

**Comment by themehdihn** [comment]
> Do you say something like this? ![image](https://private-user-images.githubusercontent.com/19741953/311817293-91d3e8e8-0015-47fd-83bf-4acda1118fe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MjAzOTYsIm5iZiI6MTcxMDUyMDA5NiwicGF0aCI6Ii8xOTc0MTk1My8zMTE4MTcyOTMtOTFkM2U4ZTgtMDAxNS00N2ZkLTgzYmYtNGFjZGExMTE4ZmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDE2MjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NDQyMjU5ZGJjMzE2NGU3N2IwMmI5ODBkZmQ5NDA1NmI2ZDE3NTgwMjkzYzJjYWI2NmM1OWJjOWMyODcxNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3fB4qTlNXq_gR-iVRdUtxJIt2lVjcQghp-BCNQDCFiw)

If you tell me this is the solution, it's fine, but how will it be exactly transferred to a specific page?

**Comment by victorsoares96** [comment]
I'm not saying this is the solution, I'm trying to understand what the author is proposing in the issue.

**Comment by victorsoares96** [comment]
@janstevcik21 can you elaborate on your question better? adding a visual example from another app would be very useful. Thanks!
