### ISSUE TITLE
Previous page appearing when navigate to end of book

### ISSUE THREAD

**Issue by jknvlvxs** [victorsoares96/epubjs-react-native#14]
I'm having a problem when navigating on book, the text is exceeding margin right, and the left page start appearing in the margin left.

I have recorded the screen to show the error, [see this video](https://drive.google.com/file/d/1BRRyIs8VeUNV7Wk5VV8uobbg1QLqAiRd/view?usp=sharing)

The width of the Render is `const { width } = Dimensions.get('window');`

**Comment by victorsoares96** [comment]
hi, i think i see this happening before in specific books, in other `.epub` files this issue occurred?

**Comment by jknvlvxs** [comment]
Yes, in every ebook that I have tested, this issue occurred

**Comment by victorsoares96** [comment]
can you send me any of those .epub you tested?

**Comment by jknvlvxs** [comment]
Sorry, I tested with this [Moby Dick](https://github.com/IDPF/epub3-samples/releases/download/20170606/moby-dick.epub) and the error didn't occurred. I think the error is in the creation of the .epub on InDesign

I will close the issue because the error is really in the .epub formation

**Comment by PrakharDT** [comment]
this same issue is coming for me as well its related to width. if can some help please comment or reopen this issue.
