### ISSUE TITLE
Sample is blank without any errors in expo app

### ISSUE THREAD

**Issue by timotech** [victorsoares96/epubjs-react-native#16]
Good day,
The sample on the home page is displaying blank without any errors on expo, what could be the cause
Please enlighten me.

Thanks

Tim

**Comment by lkathke** [comment]
Had the same issue. It seems, that it takes a few seconds (~10) to load the sample book.

**Comment by timotech** [comment]
Hi @lkathke thanks for your reply. I will try it further, because I waited for over 30 seconds and nothing was displaying. I will wait for at least 5 minutes and see if it shows.
But there should be a way to display an indicator to show the file is loading.
Thanks

**Comment by victorsoares96** [comment]
hi @timotech! actually in some cases the file is taking longer than usual to load for some reason.. I'll investigate that!

**Comment by timotech** [comment]
Ok thanks @victorsoares96, I will expect your findings, and probably a way out. Thanks
