### ISSUE TITLE
text selection, bookmark

### ISSUE THREAD

**Issue by alizain-memorymaps** [victorsoares96/epubjs-react-native#240]
### Summary

Hi there, I'm new to the epub world and I integrated this in my React native app but now I'm not able to select text or add a bookmark. I have seen examples in the repo but I didn't quite get the concept to add (there is code for removing). is there any example where I can see how to select a text and open a popup upon selection.

import {Reader, ReaderProvider, useReader} from '@epubjs-react-native/core';
import {useFileSystem} from '@epubjs-react-native/file-system';
import {Text, TouchableOpacity, View, useWindowDimensions} from 'react-native';
import GestureRecognizer, {swipeDirections} from 'react-native-swipe-gestures';
import AABText from '../../../components/AABText';
import {setBookChapters} from '../../../redux/slices/bookSlice';
import {useDispatch} from 'react-redux';
import {useEffect} from 'react';
// import {dark} from './styles';

const themes = {
  dark: {
    body: {
      background: '#000000',
    },
    span: {
      color: '#fff !important',
    },
    p: {
      color: '#fff !important',
    },
    li: {
      color: '#fff !important',
    },
    h1: {
      color: '#fff !important',
    },
    h2: {
      color: '#fff !important',
    },
    h3: {
      color: '#fff !important',
    },
    h4: {
      color: '#fff !important',
    },
    a: {
      color: '#fff !important',
      'pointer-events': 'auto',
      cursor: 'pointer',
    },
    '::selection': {
      background: 'lightskyblue',
    },
  },
  light: {
    body: {
      background: '#fff',
    },
    span: {
      color: '#000 !important',
    },
    p: {
      color: '#000 !important',
      // lineHeight: '100px',
    },
    li: {
      color: '#000 !important',
    },
    h1: {
      color: '#000 !important',
    },
    a: {
      color: '#000 !important',
      'pointer-events': 'auto',
      cursor: 'pointer',
    },
    '::selection': {
      background: 'lightskyblue',
    },
  },
};
const dark = {
  body: {
    background: '#000000',
  },
  span: {
    color: '#fff !important',
  },
  p: {
    color: '#fff !important',
  },
  li: {
    color: '#fff !important',
  },
  h1: {
    color: '#fff !important',
  },
  h2: {
    color: '#fff !important',
  },
  h3: {
    color: '#fff !important',
  },
  h4: {
    color: '#fff !important',
  },
  a: {
    color: '#fff !important',
    'pointer-events': 'auto',
    cursor: 'pointer',
  },
  '::selection': {
    background: 'lightskyblue',
  },
};

function Inner({link, setNavigation, fontSize, fontFamily, theme, lineheight}) {
  const {width, height} = useWindowDimensions();
  const {
    addMark,
    removeMark,
    goNext,
    goPrevious,
    getMeta,
    getLocations,
    changeTheme,
    getCurrentLocation,
    changeFontFamily,
    changeFontSize,
  } = useReader();

  const handleAddMark = (text, cfiRange) => {
    addMark(text, cfiRange);
  };

  useEffect(() => {
    changeFontFamily(fontFamily);
    changeFontSize(`${fontSize}px`);
    const customizedTheme = {...themes[theme]};
    // Assuming `p` tag is what you want to target, but adjust as necessary
    customizedTheme.p = {
      ...customizedTheme.p,
      lineHeight: `${lineheight}% !important`, // Apply dynamic line height
    };

    changeTheme(customizedTheme);
  }, [fontSize, fontFamily, theme, lineheight]);

  const curLoc = getCurrentLocation();
  const onSwipe = (gestureName, gestureState) => {
    // console.log(gestureName, gestureState);

    const {SWIPE_UP, SWIPE_DOWN, SWIPE_LEFT, SWIPE_RIGHT} = swipeDirections;

    switch (gestureName) {
      case SWIPE_LEFT:
        goNext();
        break;
      case SWIPE_RIGHT:
        goPrevious();
        break;
    }
  };
  const config = {
    velocityThreshold: 0.3,
    directionalOffsetThreshold: 80,
  };

  // Function to handle text selection
  const handleTextSelection = selectedText => {
    // Display an alert or your custom popup here
    Alert.alert('Text Selected', selectedText, [{text: 'OK'}]);
  };

  // console.log(getLocations());

  return (
    <>
      <GestureRecognizer
        onSwipe={(direction, state) => onSwipe(direction, state)}
        config={config}
        // style={{borderWidth: 1}}
      >
        {/* <TouchableOpacity onPress={() => changeTheme(dark)}>
          <Text>hello</Text>
        </TouchableOpacity> */}

        <Reader
          src={link}
          width={width - 38}
          height={height - 280}
          fileSystem={useFileSystem}
          onNavigationLoaded={e => {
            // console.log(e, 'nav');
            setNavigation(e);
          }}
          defaultTheme={'light'}
          onSelected={e => console.log(e)}
          enableSelection
          enableSwipe
          onMarkPressed={e => console.log(e)}
        />
      </GestureRecognizer>
      <View
        style={{justifyContent: 'center', alignItems: 'center', marginTop: 10}}>
        <AABText>Page 3/12 of this section</AABText>
      </View>
    </>
  );
}

const BookContainer = ({
  link,
  fontSize,
  fontFamily,
  theme,
  lineheight = 18,
}) => {
  const dispatch = useDispatch();
  return (
    <ReaderProvider>
      <Inner
        link={link}
        setNavigation={nav => dispatch(setBookChapters(nav))}
        fontSize={fontSize}
        fontFamily={fontFamily}
        theme={theme}
        lineheight={lineheight}
      />
    </ReaderProvider>
  );
};

export default BookContainer;

### What platform(s) does this occur on?

Android, iOS

### Environment

N/A

### Minimal reproducible example

N/A

**Comment by victorsoares96** [comment]
Hi @alizain-memorymaps please use the latest beta version with new annotations and bookmark features:

```sh
npm i @epubjs-react-native/core@beta
```

**Comment by alizain-memorymaps** [comment]
ok @victorsoares96 thankyou for the reply. let me do this.

**Comment by victorsoares96** [comment]
i'll close this issue, you could reopen this issue again if you need
