### ISSUE TITLE
Do you know why i got this error while opening book?

### ISSUE THREAD

**Issue by rashidwiizb** [victorsoares96/epubjs-react-native#247]
Do you know why i got this error while opening book?

domain undefineed 
error code: 1
 WARN  Encountered an error loading page {"canGoBack": false, "canGoForward": false, "code": -1, "description": "net::ERR_ACCESS_DENIED", "loading": false, "target": 5927, "title": "", "url": "file:///data/user/0/com.alrajhieducation.kutubiapp/filesindex.html"}
 
 
![Screenshot_1712921643](https://github.com/victorsoares96/epubjs-react-native/assets/137061001/418f0cc6-3ecf-4994-a01e-ac35f4d581f3)

_Originally posted by @rashidwiizb in https://github.com/victorsoares96/epubjs-react-native/issues/222#issuecomment-2056698371_

**Comment by jihedlab** [comment]
Hi @rashidwiizb did you solve this issue? I am facing the same problem.

**Comment by rashidwiizb** [comment]
@jihedlab yes

**Comment by jihedlab** [comment]
Would you mind elaborating?
