### ISSUE TITLE
Error: failed to write jszip js file (loading stuck at 0%)

### ISSUE THREAD

**Issue by kaushil111** [victorsoares96/epubjs-react-native#249]
### Summary

This is the first time I am trying out the epub reader. Congratulations on your release! I have a bare react-native project with:
```
package.json

{
  ...
  dependencies: {
    "@epubjs-react-native/core": "^1.4.0",
    "@epubjs-react-native/file-system": "^1.1.2",
    ...
    "react": "18.2.0",
    "react-native": "0.72.7",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.16.0",
    "react-native-webview": "^13.8.6",
  }
}
```

I can successfully load the example URL `https://s3.amazonaws.com/moby-dick/OPS/package.opf` onto my simulator. The problem occurs when I try to load the same URL and setup on a device. The reader is stuck at 0% with warning box with the following error:
![Screenshot 2024-04-18 at 12 28 12 AM](https://github.com/victorsoares96/epubjs-react-native/assets/8789305/0d5c41e6-240b-409a-9fd3-72f6f024ef7e)

I ran the bare example on the device, and it replicates the error. Let me know if there is anything I can help with, thanks in advance!

### What platform(s) does this occur on?

iOS

### Environment
```
{
  ...
  dependencies: {
    "@epubjs-react-native/core": "^1.4.0",
    "@epubjs-react-native/file-system": "^1.1.2",
    ...
    "react": "18.2.0",
    "react-native": "0.72.7",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.16.0",
    "react-native-webview": "^13.8.6",
  }
}
```

### Minimal reproducible example

https://github.com/victorsoares96/epubjs-react-native/tree/master/example-bare

**Comment by victorsoares96** [comment]
thanks for share, i'll work in this soon as possible!

**Comment by victorsoares96** [comment]
Its seems to be a permission issue..

I found a similar issue in stackoverflow, i'll test soon if this solves the problem. I place the link below if you to desire apply this fix

https://stackoverflow.com/questions/54626359/react-native-fs-ios-not-showing-files-in-the-document-directory

**Comment by kaushil111** [comment]
> Its seems to be a permission issue..
> 
> I found a similar issue in stackoverflow, i'll test soon if this solves the problem. I place the link below if you to desire apply this fix
> 
> https://stackoverflow.com/questions/54626359/react-native-fs-ios-not-showing-files-in-the-document-directory

Thanks for the share, let me test and get back to you on this

**Comment by kaushil111** [comment]
@victorsoares96 one more thing that was causing the failures: https://github.com/victorsoares96/epubjs-react-native/pull/250

**Comment by victorsoares96** [comment]
@kaushil111 thanks for your help, i'll see your pull request
