### ISSUE TITLE
Not Opening on real device

### ISSUE THREAD

**Issue by paulNIP** [victorsoares96/epubjs-react-native#255]
Been experiencing issue of opening epub on IOS device on an emulator the it easily works but when on a real device it does not open any help is highly appreciated

**Comment by victorsoares96** [comment]
please see the installation steps in specific Info.plist section
https://github.com/victorsoares96/epubjs-react-native?tab=readme-ov-file#installation

**Comment by rashidwiizb** [comment]
i am using this versions 
    "@epubjs-react-native/core": "1.4.0-beta.45",
    "@epubjs-react-native/file-system": "^1.1.2",
        "react-native": "0.72.12",
    "react-native-webview": "^13.8.5",
    "react-native-gesture-handler": "^2.16.0",

and i add <key>LSSupportsOpeningDocumentsInPlace</key>
<true/> this to info.plist but experiencing issue of opening epub on IOS real device (stuck in loading 0%) but not in ios simulators

**Comment by victorsoares96** [comment]
try run `npx pod-install` in your ios directory again after add LSSupportsOpeningDocumentsInPlace key

**Comment by victorsoares96** [comment]
and use @epubjs-react-native/core: "1.4.1

**Comment by rashidwiizb** [comment]
Is this version have injectjavascript function? Also when i try npx pod install my system ask me a path . So do u have any idea on which path should i give

**Comment by victorsoares96** [comment]
Yeah, this version have injectJs and contains the fix for this issue.. about pod install you can run `npx pod-install ios` inside root of your react native project, the first argument after `npx pod-install` is a path where project ios files are located

**Comment by farshed** [comment]
I'm developing with expo and facing the same issue on iOS.

**Comment by victorsoares96** [comment]
> I'm developing with expo and facing the same issue on iOS. It works fine when the src is a remote file but not when it's local.

check if you use the latest version(1.4.1) and see the installation steps in specific Info.plist section
https://github.com/victorsoares96/epubjs-react-native?tab=readme-ov-file#installation

**Comment by victorsoares96** [comment]
Try to add key mentioned above in expo app.json, see more in expo docs:

{
  "ios": {
    "infoPlist": {
  "LSSupportsOpeningDocumentsInPlace": true
    }
  }
}

https://docs.expo.dev/guides/permissions/#ios

**Comment by victorsoares96** [comment]
And if you use expo managed project with expo-document-picker try to use this:

```ts
const { assets } = await DocumentPicker.getDocumentAsync({ copyToCacheDirectory: false });
```

**Comment by farshed** [comment]
Adding `LSSupportsOpeningDocumentsInPlace` to info.plist and setting `copyToCacheDirectory` to false on iOS worked. Thanks.

**Comment by victorsoares96** [comment]
awesome! i'll close this issue, the author can reopen if need
