### ISSUE TITLE
GoToPrevious() issue.

### ISSUE THREAD

**Issue by sw-tt-ankitborad** [victorsoares96/epubjs-react-native#256]
### Summary

When we go second page(start with top) and scroll down, then go to the previous page, so it's display bottom content of first page.
We have atteacting below code and funcation.

 const {goPrevious, goNext} = useReader();      // we are using this method for next or previous page.

<Reader
              height={viewHeight - 45}
              src={epubURL}
              fileSystem={useFileSystem}
              flow="scrolled-doc" />
              
So please check and provide solution ASAP.

### What platform(s) does this occur on?

Android, iOS

### Environment

 const {goPrevious, goNext} = useReader();      // we are using this method for next or previous page.

<Reader
              height={viewHeight - 45}
              src={epubURL}
              fileSystem={useFileSystem}
              flow="scrolled-doc" />

### Minimal reproducible example

When we go second page(start with top) and scroll down, then go to the previous page, so it's display bottom content of first page.

**Comment by sw-tt-hitendrachavda** [comment]
i am facing the same issue.

**Comment by victorsoares96** [comment]
Thank you for reporting this problem, I resolved it in the mentioned pull request, please update the library to the latest version (1.4.2)

**Comment by sw-tt-ankitborad** [comment]
It's finally functioning as anticipated. Appreciate the assistance!
