### ISSUE TITLE
Image Not Display in Center

### ISSUE THREAD

**Issue by sw-tt-ankitborad** [victorsoares96/epubjs-react-native#260]
### Summary

I have displayed a video with an epub file in landscape and portrait mode. But not display image proper(in center) in both the mode. I am attaching below snap shot
![Simulator Screen Shot - iPhone 14 - 2024-05-09 at 16 30 16](https://github.com/victorsoares96/epubjs-react-native/assets/98322484/b990dd97-6a20-4bc1-8533-9842c41ab086)
![Simulator Screen Shot - iPhone 14 - 2024-05-09 at 16 29 48](https://github.com/victorsoares96/epubjs-react-native/assets/98322484/bc02ba28-b457-40e8-8b29-303ad8cfcebb)

### What platform(s) does this occur on?

Android, iOS

### Environment

Getting same issue in for Environment

### Minimal reproducible example

I have displayed a video with an epub file in landscape and portrait mode. But not display image proper(in center) in both the mode. I am attaching below snap shot
![Simulator Screen Shot - iPhone 14 - 2024-05-09 at 16 30 16](https://github.com/victorsoares96/epubjs-react-native/assets/98322484/b990dd97-6a20-4bc1-8533-9842c41ab086)
![Simulator Screen Shot - iPhone 14 - 2024-05-09 at 16 29 48](https://github.com/victorsoares96/epubjs-react-native/assets/98322484/bc02ba28-b457-40e8-8b29-303ad8cfcebb)

**Comment by sw-tt-hitendrachavda** [comment]
We are using atEnd and atStart property for disable the next, previous button. but we are not getting proper value. so please check and resolve asap.

**Comment by victorsoares96** [comment]
Hello! You can provide this epub file?

**Comment by sw-tt-ankitborad** [comment]
>>> We have attached a zip file (Epub is not supported). Please check the attached epub file in landscape mode with a 50% width.


[EBOOK_19a428d3-73b3-4260-af96-a7fb19862367.zip](https://github.com/victorsoares96/epubjs-react-native/files/15290043/EBOOK_19a428d3-73b3-4260-af96-a7fb19862367.zip)
