### ISSUE TITLE
[WARN] Error evaluating injectedJavaScript: This is possibly due to an unsupported return type.

### ISSUE THREAD

**Issue by andrebeolchi** [victorsoares96/epubjs-react-native#261]
### Summary

When location is change this warn appears:

 WARN  Error evaluating injectedJavaScript: This is possibly due to an unsupported return type. Try adding true to the end of your injectedJavaScript string. Error Domain=WKErrorDomain Code=5 "JavaScript execution returned a result of an unsupported type" UserInfo={NSLocalizedDescription=JavaScript execution returned a result of an unsupported type}

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 3.7.1 - /usr/local/bin/fish
    Binaries:
      Node: 21.7.2 - /usr/local/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.5.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /Users/andrebeolchi/.rvm/rubies/ruby-3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.17 => 50.0.17 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 7.8.2
      expo-cli: 6.3.2
    Expo Workflow: bare

### Minimal reproducible example

iphone 15 pro - ios 17

```
import { Reader, Section } from '@epubjs-react-native/core';
import { useFileSystem } from '@epubjs-react-native/expo-file-system';

    <GestureHandlerRootView style={{ flex: 1 }}>
      <Reader
        src="https://s3.amazonaws.com/moby-dick/OPS/package.opf"
        fileSystem={useFileSystem}
        waitForLocationsReady
        allowScriptedContent
      />
    </GestureHandlerRootView>
```

**Comment by andrebeolchi** [comment]
Fix after reinstall dependencies and recreating ios/ folder

**Comment by andrebeolchi** [comment]
whoops, not fix

**Comment by andrebeolchi** [comment]
The error seems to be with the "section" functionality, here it is not being updated correctly, I will not be able to use for now. I'm trying to see if I can fix it, but I don't know exactly the best way to debug

I'm inside _node_modules/@epubjs-react-native/core_ lol

**Comment by victorsoares96** [comment]
thanks for report @andrebeolchi, i'll trying to see this asap

**Comment by blanck** [comment]
Also got this error and got rid of the warnings if adding `true;` to the end of function injectJavaScript in file webViewInjectFunctions.js. Might not be the correct place to fix the bug but a hint on where the error occurs.

```javascript
function injectJavaScript(ref, script) {
  ref.current?.injectJavaScript(`
    try {
      ${script}
    } catch (error) {
      alert(error?.message);
    };
    true;
  `);
}
```

**Comment by Kirillsocivka** [comment]
+1
