### ISSUE TITLE
Orientation issue

### ISSUE THREAD

**Issue by sw-tt-hitendrachavda** [victorsoares96/epubjs-react-native#281]
### Summary

When i rotate the device i am getting the wrong size and it showing half.

The below is the code for reading the ebook file.

<Reader
            width={viewWidth}
            height={viewHeight}
            fileSystem={useFileSystem}
            src={epubURL}
            flow="scrolled-doc"
 />
 
So please check and provide solution ASAP.

### What platform(s) does this occur on?

Android, iOS

### Environment

expo-env-info@1.2.0

### Minimal reproducible example

Just rotate the device landscape to PORTRAIT and PORTRAIT to LANDSCAPE.
![IMG_0423](https://github.com/victorsoares96/epubjs-react-native/assets/116159775/1174822f-e6c5-4e41-88d1-c5b98715f6c5)
![IMG_0424](https://github.com/victorsoares96/epubjs-react-native/assets/116159775/f5951468-a0f8-45c8-9c76-1dd1576b6b0e)

**Comment by victorsoares96** [comment]
You're using `width`and `height` prop? Please show me the code
