### ISSUE TITLE
Current percentage not working for epubs

### ISSUE THREAD

**Issue by artisanphil** [victorsoares96/epubjs-react-native#282]
### Summary

When using a slider, it won't update the current percentage for epub files, but it works with opf. I was wondering if this a known issue and if it is actually preferable to use opf files (is performance better)?

### What platform(s) does this occur on?

Android

### What workflow(s) does this occur on?

Expo Workflow

### Environment (or package.json)

{
  "dependencies": {
    "@epubjs-react-native/core": "latest",
    "@epubjs-react-native/expo-file-system": "latest",
    "@expo/metro-runtime": "~3.2.1",
    "@expo/vector-icons": "^14.0.0",
    "@gorhom/bottom-sheet": "^4",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-community/slider": "^4.5.2",
    "@react-navigation/native": "^6.1.15",
    "@react-navigation/native-stack": "^6.9.24",
    "expo": "^51.0.8",
    "expo-document-picker": "~12.0.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.1",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-paper": "^5.12.3",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-vector-icons": "^10.0.3",
    "react-native-web": "~0.19.6",
    "react-native-webview": "13.8.6",
    "usehooks-ts": "^3.1.0",
    "expo-router": "~3.5.15",
    "expo-linking": "~6.3.1",
    "expo-constants": "~16.0.2",
    "expo-status-bar": "~1.12.1"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@types/react": "~18.2.14",
    "typescript": "~5.3.3"
  },
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "version": "1.0.0",
  "private": true,
  "name": "example-expo",
  "main": "expo-router/entry"
}

### Your .epub file

https://www.clozetesting.com/readdaily/roblox/book.epub

### Minimal reproducible example

I tried by changing to above epub file using the WithSlider template in the example-expo folder

### I confirm that i have

- [X] I looked for a solution to my problem in other open and resolved issues
- [X] I checked the [examples](https://github.com/victorsoares96/epubjs-react-native/blob/master/docs/EXAMPLES.md) provided solve my problem
- [X] I have verified that my problem is not caused by a third-party library
- [X] I cloned the project environment [examples](https://github.com/victorsoares96/epubjs-react-native/tree/master/example-bare) and still the problem persists
- [X] I'm using the latest available version of the library and its [complements](https://www.npmjs.com/package/@epubjs-react-native/file-system)

**Comment by victorsoares96** [comment]
Thanks for the report @artisanphil! The fix will be released in version 1.4.5 soon

**Comment by artisanphil** [comment]
@victorsoares96 Thanks a lot. It works now.
