### ISSUE TITLE
Book Pages position got disturbed when try to select multiple lines or swiping fast

### ISSUE THREAD

**Issue by TalhaAbbas55** [victorsoares96/epubjs-react-native#285]
### Summary

I am working on a React native epub book reader for both IOS and Android, 
the problem is that if we select one of the lines to highlight the text and drag the selected text to multiple lines or along the boundary of the mobile, the page position gets disturbed 

<img width="331" alt="image" src="https://github.com/victorsoares96/epubjs-react-native/assets/75223616/d2a78374-befd-4013-9de2-15f52393190f">

<img width="266" alt="image" src="https://github.com/victorsoares96/epubjs-react-native/assets/75223616/8bd852b1-885a-4492-8eee-005acdf9bc54">

I tried to change the highlight color option model but still the problem was same
this is very bad for the user, I am looking for the solution but cannot understand what the problem is 

### What platform(s) does this occur on?

Android, iOS

### What workflow(s) does this occur on?

Bare Workflow

### Environment (or package.json)

{
  "name": "aabBooksMobile",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "patch-package && react-native start",
    "test": "jest",
    "android-wifi": "adb kill-server && adb tcpip 5555 && adb connect 192.168.0.32:5555 && adb devices"
  },
  "dependencies": {
    "@epubjs-react-native/core": "^1.4.4",
    "@epubjs-react-native/file-system": "^1.1.2",
    "@gorhom/bottom-sheet": "^4.6.1",
    "@react-native-async-storage/async-storage": "^1.22.3",
    "@react-native-clipboard/clipboard": "^1.14.1",
    "@react-navigation/bottom-tabs": "^6.5.19",
    "@react-navigation/native": "^6.1.16",
    "@react-navigation/native-stack": "^6.9.25",
    "@reduxjs/toolkit": "^2.2.2",
    "axios": "^1.6.8",
    "eventemitter3": "^5.0.1",
    "patch-package": "^8.0.0",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-bouncy-checkbox": "^3.0.7",
    "react-native-dropdown-select-list": "^2.0.5",
    "react-native-element-dropdown": "^2.10.4",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.16.0",
    "react-native-global-font": "^1.0.3",
    "react-native-popup-menu": "^0.16.1",
    "react-native-range-slider": "^0.1.2",
    "react-native-raw-bottom-sheet": "^3.0.0",
    "react-native-reanimated": "^3.8.1",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.29.0",
    "react-native-simple-dialogs": "^2.0.3",
    "react-native-snap-carousel": "^4.0.0-beta.6",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-webview": "^13.8.4",
    "react-redux": "^9.1.0",
    "rn-range-slider": "^2.2.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.73.21",
    "@react-native/eslint-config": "0.73.2",
    "@react-native/js-polyfills": "^0.75.0-main",
    "@react-native/metro-babel-transformer": "^0.75.0-main",
    "@react-native/metro-config": "^0.73.5",
    "@react-native/typescript-config": "0.73.1",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "metro-config": "^0.80.7",
    "metro-runtime": "^0.80.7",
    "prettier": "2.8.8",
    "react-native-svg": "^15.1.0",
    "react-native-svg-transformer": "^1.3.0",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}

### Your .epub file

https://aab-book-stag.s3.eu-west-2.amazonaws.com/65718a24835592f22a309948/9780853304029.epub

### Minimal reproducible example

I have reproduced the bug with your [basic-example](https://github.com/victorsoares96/epubjs-react-native/blob/master/example-bare/examples/Basic/index.tsx); 
changing the code like this 

```
import * as React from 'react';
import {SafeAreaView} from 'react-native';
import {Reader, ReaderProvider, useReader} from '@epubjs-react-native/core';
import {useFileSystem} from '@epubjs-react-native/file-system';

export default function Basic() {
  const {addAnnotation, removeAnnotation, annotations} = useReader();

  return (
    <SafeAreaView style={{flex: 1}}>
      {/* <ReaderProvider> */}
      <Reader
        src="https://s3.amazonaws.com/moby-dick/OPS/package.opf"
        fileSystem={useFileSystem}
        enableSelection
        menuItems={[
          {
            label: '🟡',
            action: cfiRange => {
              addAnnotation('highlight', cfiRange, undefined, {
                color: COLORS[2],
              });
              return true;
            },
          },
          {
            label: '🔴',
            action: cfiRange => {
              addAnnotation('highlight', cfiRange, undefined, {
                color: COLORS[0],
              });
              return true;
            },
          },
          {
            label: '🟢',
            action: cfiRange => {
              addAnnotation('highlight', cfiRange, undefined, {
                color: COLORS[3],
              });
              return true;
            },
          },
          {
            label: 'Add Note',
            action: (cfiRange, text) => {
              setSelection({cfiRange, text});
              addAnnotation('highlight', cfiRange, {isTemp: true});
              annotationsListRef.current?.present();
              return true;
            },
          },
        ]}
      />
      {/* </ReaderProvider> */}
    </SafeAreaView>
  );
}
```

just select some text and grab one of the selection handles, then move that selection handle along with all corners of the mobile, it will show like this

<img width="330" alt="image" src="https://github.com/victorsoares96/epubjs-react-native/assets/75223616/43623332-a1de-462c-b79e-51be7c58351f">

and then it remains like this even if you navigate between pages

<img width="333" alt="image" src="https://github.com/victorsoares96/epubjs-react-native/assets/75223616/a7b40284-5fb7-47cc-baa3-23ba51dd9e08">

### I confirm that i have

- [X] I looked for a solution to my problem in other open and resolved issues
- [X] I checked the [examples](https://github.com/victorsoares96/epubjs-react-native/blob/master/docs/EXAMPLES.md) provided solve my problem
- [X] I cloned the project environment [examples](https://github.com/victorsoares96/epubjs-react-native/tree/master/example-bare) and still the problem persists
- [X] I have verified that my problem is not caused by a third-party library
- [X] I'm using the latest available version of the library and its [complements](https://www.npmjs.com/package/@epubjs-react-native/file-system)

**Comment by victorsoares96** [comment]
thanks for share, i'll see this asap

**Comment by victorsoares96** [comment]
@TalhaAbbas55 not yet, I'm busy at the moment... probably this month I'll check it out

**Comment by piotr-graczyk-gmi** [comment]
@victorsoares96 Did you look at on it?

**Comment by TalhaAbbas55** [comment]
Hi @victorsoares96, hope you are doing well, any solution you got for this problem?

**Comment by victorsoares96** [comment]
No news about this at the moment, it's not being something easy to get around 😢

**Comment by dcallus** [comment]
Having this issue as well on Android. It also appears to be a bug on epubjs-reader with no solution yet.

**Comment by dcallus** [comment]
> ### Summary
> 
> I am working on a React native epub book reader for both IOS and Android, the problem is that if we select one of the lines to highlight the text and drag the selected text to multiple lines or along the boundary of the mobile, the page position gets disturbed
> 
> <img alt="image" width="331" src="https://private-user-images.githubusercontent.com/75223616/343134484-d2a78374-befd-4013-9de2-15f52393190f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgwNDc0MzcsIm5iZiI6MTczODA0NzEzNywicGF0aCI6Ii83NTIyMzYxNi8zNDMxMzQ0ODQtZDJhNzgzNzQtYmVmZC00MDEzLTlkZTItMTVmNTIzOTMxOTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI4VDA2NTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZjdmOTc5MmZhMWZkOGFjNmI0YmE2ZDg2ZjBkNGZiYjgxNjdmNjBkMzg5YzliOGYzNjZkMTI3YWY1ZWRiOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7MzY49O-LDX_Mq2Sf643MX60fA_53g4f8oXsRPj4xz0"> <img alt="image" width="266" src="https://private-user-images.githubusercontent.com/75223616/343134603-8bd852b1-885a-4492-8eee-005acdf9bc54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgwNDc0MzcsIm5iZiI6MTczODA0NzEzNywicGF0aCI6Ii83NTIyMzYxNi8zNDMxMzQ2MDMtOGJkODUyYjEtODg1YS00NDkyLThlZWUtMDA1YWNkZjliYzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI4VDA2NTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZDAyZGMxMDEwZWU0ZDJmZjQ2MjhjNzIwYjMxNWE5ZDcxMzUxNjI5MDIxZTdlNTAyNDg1ZDAzZjE5NzdiZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ETU6sCIVoFwlX9-meiuVkZ0fI5Y38ksFlLLK75G0tzA">
> I tried to change the highlight color option model but still the problem was same this is very bad for the user, I am looking for the solution but cannot understand what the problem is
> 
> ### What platform(s) does this occur on?
> 
> Android, iOS
> 
> ### What workflow(s) does this occur on?
> 
> Bare Workflow
> 
> ### Environment (or package.json)
> 
> { "name": "aabBooksMobile", "version": "0.0.1", "private": true, "scripts": { "android": "react-native run-android", "ios": "react-native run-ios", "lint": "eslint .", "start": "patch-package && react-native start", "test": "jest", "android-wifi": "adb kill-server && adb tcpip 5555 && adb connect 192.168.0.32:5555 && adb devices" }, "dependencies": { "@epubjs-react-native/core": "^1.4.4", "@epubjs-react-native/file-system": "^1.1.2", "@gorhom/bottom-sheet": "^4.6.1", "@react-native-async-storage/async-storage": "^1.22.3", "@react-native-clipboard/clipboard": "^1.14.1", "@react-navigation/bottom-tabs": "^6.5.19", "@react-navigation/native": "^6.1.16", "@react-navigation/native-stack": "^6.9.25", "@reduxjs/toolkit": "^2.2.2", "axios": "^1.6.8", "eventemitter3": "^5.0.1", "patch-package": "^8.0.0", "react": "18.2.0", "react-native": "0.73.6", "react-native-bouncy-checkbox": "^3.0.7", "react-native-dropdown-select-list": "^2.0.5", "react-native-element-dropdown": "^2.10.4", "react-native-fs": "^2.20.0", "react-native-gesture-handler": "^2.16.0", "react-native-global-font": "^1.0.3", "react-native-popup-menu": "^0.16.1", "react-native-range-slider": "^0.1.2", "react-native-raw-bottom-sheet": "^3.0.0", "react-native-reanimated": "^3.8.1", "react-native-reanimated-carousel": "^3.5.1", "react-native-safe-area-context": "^4.9.0", "react-native-screens": "^3.29.0", "react-native-simple-dialogs": "^2.0.3", "react-native-snap-carousel": "^4.0.0-beta.6", "react-native-swipe-gestures": "^1.0.5", "react-native-webview": "^13.8.4", "react-redux": "^9.1.0", "rn-range-slider": "^2.2.2" }, "devDependencies": { "@babel/core": "^7.20.0", "@babel/preset-env": "^7.20.0", "@babel/runtime": "^7.20.0", "@react-native/babel-preset": "0.73.21", "@react-native/eslint-config": "0.73.2", "@react-native/js-polyfills": "^0.75.0-main", "@react-native/metro-babel-transformer": "^0.75.0-main", "@react-native/metro-config": "^0.73.5", "@react-native/typescript-config": "0.73.1", "@types/react": "^18.2.6", "@types/react-test-renderer": "^18.0.0", "babel-jest": "^29.6.3", "eslint": "^8.19.0", "jest": "^29.6.3", "metro-config": "^0.80.7", "metro-runtime": "^0.80.7", "prettier": "2.8.8", "react-native-svg": "^15.1.0", "react-native-svg-transformer": "^1.3.0", "react-test-renderer": "18.2.0", "typescript": "5.0.4" }, "engines": { "node": ">=18" } }
> 
> ### Your .epub file
> 
> https://aab-book-stag.s3.eu-west-2.amazonaws.com/65718a24835592f22a309948/9780853304029.epub
> 
> ### Minimal reproducible example
> 
> I have reproduced the bug with your [basic-example](https://github.com/victorsoares96/epubjs-react-native/blob/master/example-bare/examples/Basic/index.tsx); changing the code like this
> 
> ```
> import * as React from 'react';
> import {SafeAreaView} from 'react-native';
> import {Reader, ReaderProvider, useReader} from '@epubjs-react-native/core';
> import {useFileSystem} from '@epubjs-react-native/file-system';
> 
> export default function Basic() {
>   const {addAnnotation, removeAnnotation, annotations} = useReader();
> 
>   return (
>     <SafeAreaView style={{flex: 1}}>
>       {/* <ReaderProvider> */}
>       <Reader
>         src="https://s3.amazonaws.com/moby-dick/OPS/package.opf"
>         fileSystem={useFileSystem}
>         enableSelection
>         menuItems={[
>           {
>             label: '🟡',
>             action: cfiRange => {
>               addAnnotation('highlight', cfiRange, undefined, {
>                 color: COLORS[2],
>               });
>               return true;
>             },
>           },
>           {
>             label: '🔴',
>             action: cfiRange => {
>               addAnnotation('highlight', cfiRange, undefined, {
>                 color: COLORS[0],
>               });
>               return true;
>             },
>           },
>           {
>             label: '🟢',
>             action: cfiRange => {
>               addAnnotation('highlight', cfiRange, undefined, {
>                 color: COLORS[3],
>               });
>               return true;
>             },
>           },
>           {
>             label: 'Add Note',
>             action: (cfiRange, text) => {
>               setSelection({cfiRange, text});
>               addAnnotation('highlight', cfiRange, {isTemp: true});
>               annotationsListRef.current?.present();
>               return true;
>             },
>           },
>         ]}
>       />
>       {/* </ReaderProvider> */}
>     </SafeAreaView>
>   );
> }
> ```
> 
> just select some text and grab one of the selection handles, then move that selection handle along with all corners of the mobile, it will show like this
> 
> <img alt="image" width="330" src="https://private-user-images.githubusercontent.com/75223616/343138059-43623332-a1de-462c-b79e-51be7c58351f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgwNDc0MzcsIm5iZiI6MTczODA0NzEzNywicGF0aCI6Ii83NTIyMzYxNi8zNDMxMzgwNTktNDM2MjMzMzItYTFkZS00NjJjLWI3OWUtNTFiZTdjNTgzNTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI4VDA2NTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzOWJhNDkxNjc4Mjk4YWU4MTVkN2JkMTRlYzk4NWUzNmMyNTk2M2NkNmVmMGI0MDM5ZmZlZmZkNDc5NjFjNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dlxuTkv9P19qK9Tfj0g1DEdYvfiXb-WD2nmFokfH_z0">
> and then it remains like this even if you navigate between pages
> 
> <img alt="image" width="333" src="https://private-user-images.githubusercontent.com/75223616/343138218-a7b40284-5fb7-47cc-baa3-23ba51dd9e08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgwNDc0MzcsIm5iZiI6MTczODA0NzEzNywicGF0aCI6Ii83NTIyMzYxNi8zNDMxMzgyMTgtYTdiNDAyODQtNWZiNy00N2NjLWJhYTMtMjNiYTUxZGQ5ZTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI4VDA2NTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiN2YzYjM0MjQ4OTllNTFlOGNhZGZhMGMwZTdhOTZkNWMwMjVhZjdjODExMDVmMDk1NTA4YmVkNzZiMzFjZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1d55SKeHbgiEN-gbuHfiB7vHUj8d0szc_tbZ5YqNU2g">
> ### I confirm that i have
> 
> * [x]  I looked for a solution to my problem in other open and resolved issues[x]  I checked the [examples](https://github.com/victorsoares96/epubjs-react-native/blob/master/docs/EXAMPLES.md) provided solve my problem[x]  I cloned the project environment [examples](https://github.com/victorsoares96/epubjs-react-native/tree/master/example-bare) and still the problem persists[x]  I have verified that my problem is not caused by a third-party library[x]  I'm using the latest available version of the library and its [complements](https://www.npmjs.com/package/@epubjs-react-native/file-system)


Hi Talha

Did you ever find a solution to this?

**Comment by jm4r7in** [comment]
@victorsoares96 There could be some work around, but the problem is that we never know when some text is select or not.
`onSelected` is not called when no text is selected.
Could it be possible to change that ?
