### ISSUE TITLE
Select whole sentence

### ISSUE THREAD

**Issue by oleksandr-serhiienko** [victorsoares96/epubjs-react-native#314]
### Summary

I am trying to expend the functionality and add an extension to the **menuItems** so I can select whole sentence. 
Normal **onSelected={handleSelected}**  works for me. But it is not clear how could I add missing logic.
I am checking the **injectJavascript** options, but I do not find there any clear way to implement it.
The example about **injectJavascript** is very good, but not very helpfull for now, and **epubjs.ts** does have the implementetion of **onSelected**, but I need some help in understanding, where my logic should be implemented

### What platform(s) does this occur on?

Android

### What workflow(s) does this occur on?

Expo Workflow

### Environment (or package.json)

expo-env-info@1.2.0

### I confirm that i have

- [X] I looked for a solution to my problem in other open and resolved issues
- [X] I checked the [examples](https://github.com/victorsoares96/epubjs-react-native/blob/master/docs/EXAMPLES.md) provided solve my problem
- [X] I have verified that my problem is not caused by a third-party library
- [X] I cloned the project environment [examples](https://github.com/victorsoares96/epubjs-react-native/tree/master/example-bare) and still the problem persists
- [X] I'm using the latest available version of the library and its [complements](https://www.npmjs.com/package/@epubjs-react-native/file-system)

**Comment by oleksandr-serhiienko** [comment]
Please, if smb has any suggestion how could I implement it, just let me know. I would be very thanfull!

**Comment by victorsoares96** [comment]
Hello! Is the functionality you want to implement based on something that already exists in another reader app? If so, can you give us some examples?

**Comment by oleksandr-serhiienko** [comment]
Hi @victorsoares96, I made a small video to show how it suppose to work. I found this functionality in DuoCard mobile app: 
https://github.com/user-attachments/assets/69646f90-bea4-44e5-b781-caa5ec1dce17
As you can see first time I press and hold to select word and other times I just double click to select whole sentence. 
I wanted to ask if you know How I could implement it?
