### ISSUE TITLE
Zooming is not working properly.

### ISSUE THREAD

**Issue by kyagie** [victorsoares96/epubjs-react-native#47]
Zooming in and out all only happens at the top left of the page. 

https://user-images.githubusercontent.com/40200357/185233550-98199c83-c9f9-491c-9d68-4a7d84899ecb.mp4

**Comment by BinMansoor11** [comment]
I'm getting this same error in iOS, android works fine though.

**Comment by BinMansoor11** [comment]
@kyagie did you find any solution for it?

**Comment by BinMansoor11** [comment]
I've solved this one.

**Comment by emanu7478** [comment]
@BinMansoor11  How do you solve this issue? I'm still facing this issue...when I zoom and swipe to the right it changes to the next page. How can I fix this issue?

**Comment by BinMansoor11** [comment]
@emanu7478 I made following changes in `@epubjs-react-native/core/src/View.tsx`:

`<WebView
      ...
      scrollEnabled={false} // for iOS
      bounces={false}
      ...
/>`
