### ISSUE TITLE
Loading stuck at 0%

### ISSUE THREAD

**Issue by Subliminalman** [victorsoares96/epubjs-react-native#49]
I'm trying to load in an epub file from a google storage bucket and it is stuck at 0%. I get this warning

`Possible Unhandled Promise Rejection (id: 0):
TypeError: source.includes is not a function. (In 'source.includes('base64,')', 'source.includes' is undefined)
getSourceType@http://10.0.0.87:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&a`

**Comment by kyagie** [comment]
I am having a similar issue on iOS.

**Comment by kyagie** [comment]
![image](https://user-images.githubusercontent.com/40200357/185754088-575cf973-4c20-4053-85f5-f4289fabac58.png)

**Comment by victorsoares96** [comment]
please, can you show me what you are passing in the `src` property?

**Comment by kyagie** [comment]
It does not open with iOS, only renders the loader. 
![image](https://user-images.githubusercontent.com/40200357/185791596-e32698c6-df9e-4652-ac28-9605f34ed6c8.png)

`<Reader
        src="https://filesamples.com/samples/ebook/epub/Sway.epub"
        // src={BookUrl}
        width={width}
        height={showHeader ? '83%' : height}
        fileSystem={useFileSystem}
        renderOpeningBookComponent={loadingComponent}
        onPress={() => setShowHeader(!showHeader)}
        defaultTheme={theme}
        initialLocation={page} `

**Comment by victorsoares96** [comment]
@kyagie please, send me your `package.json`

**Comment by kyagie** [comment]
> @kyagie please, send me your `package.json`
This issue happens most on physical iOS devices. It works perfectly well on the simulator. 
![image](https://user-images.githubusercontent.com/40200357/186445706-c868628f-0a57-412c-9396-142826ae0228.png)

![image](https://user-images.githubusercontent.com/40200357/186445773-8ab36ae7-19e4-42e9-bf4c-7dc9e7ade686.png)

**Comment by victorsoares96** [comment]
it looks like you are using the latest versions of `react` and `react-native`, unfortunately I haven't tested this libraries with these versions yet.. try to downgrade to the versions that are in the examples in the repository. as soon as possible i will check this further

**Comment by kyagie** [comment]
Hi

-- 
A.k.k

**Comment by D3troit98** [comment]
I'm using the latest version and it's works

**Comment by PrakharDT** [comment]
@kyagie can you please share some sample codes

**Comment by siphu** [comment]
Same issue as #57 
There's an issue loading local files after it downloads the epub. file

**Comment by victorsoares96** [comment]
This problem was resolved in the last version released, I will be closing this issue.. if you want, the author can reopen it
