### ISSUE TITLE
useReader Hooks not working

### ISSUE THREAD

**Issue by bharamalhusen** [victorsoares96/epubjs-react-native#5]
i successfully run epubjs-react-native 
but i use goNext method which is not working for me also other methods are also not working 

Below i attached my sample code
```
import * as React from 'react';
import {View, ActivityIndicator} from 'react-native';
import {Button, useWindowDimensions} from 'react-native';
import {Reader, ReaderProvider, useReader} from 'epubjs-react-native';

export default function CustomReader() {
  const {width, height} = useWindowDimensions();
  const {goNext, changeTheme} = useReader();
  
  return (
      <ReaderProvider>
        <Reader
          ref={ref => (this.reader = ref)}
          src={{uri: 'https://s3.amazonaws.com/moby-dick/OPS/package.opf'}}
          width={width}
          height={height - 200}
          enableSelection={true}
        />
      </ReaderProvider>
      <Button
        title="Next Page"
        onPress={() => {
          goNext()
        }}
      />
  );
}
```

Thanks

https://user-images.githubusercontent.com/20451218/152643393-a113c54d-814c-42ad-a1fa-4c89c6854bd2.mov

**Comment by fabiancarlos** [comment]
Why was closed? I having this issue too.

**Comment by fabiancarlos** [comment]
Somehow... i discover, that in a model not dont works. I think was a issue about the ref of the ReaderProvider,

**Comment by anwersolangi** [comment]
I was also facing this issue, I think the documentation needs to be updated, but if you need a solution, follow this:
https://github.com/victorsoares96/epubjs-react-native/issues/9#issuecomment-1100117103

**Comment by divyanshkumarsharma** [comment]
Still this issue is there is there anyone to solve this ??
