### ISSUE TITLE
How to use useReader()

### ISSUE THREAD

**Issue by divyanshkumarsharma** [victorsoares96/epubjs-react-native#50]
i want to change the font size on double tab i am getting the event onDoubleTab but not able to interact with the changeFontSize property??? 

can anyone help

**Comment by victorsoares96** [comment]
do you using `useReader` inside `ReaderProvider`? Please show me your code

**Comment by divyanshkumarsharma** [comment]
import * as React from 'react';

import { SafeAreaView, useWindowDimensions } from 'react-native';
import { Reader, ReaderProvider, useReader } from '@epubjs-react-native/core';
import { useFileSystem } from '@epubjs-react-native/file-system';
const App = () => {
    const { width, height } = useWindowDimensions();
    const [file, setFile] = React.useState(null)
    const {
        changeFontSize
    } = useReader()

    return (
        <SafeAreaView>
            <ReaderProvider >
                <Reader
                    registerBook={(sa) => use.current = sa}
                    src="https://s3.amazonaws.com/moby-dick/OPS/package.opf"
                    width={width}
                    height={height}
                    fileSystem={useFileSystem}

                    onDoublePress={(selected) => {
                        changeFontSize("50px")
                        console.log("onDoublePress")
                    }}
                />
            </ReaderProvider>
        </SafeAreaView>
    );
}
export default App;

**Comment by divyanshkumarsharma** [comment]
This is the code snippet i have to change the font size on double press but its not reflecting anything???

**Comment by divyanshkumarsharma** [comment]
can you help??

**Comment by victorsoares96** [comment]
I see that you are using the `useReader` hook outside the `ReaderProvider`, you need to use this hook inside this `ReaderProvider` so that it can work as expected. you can see examples [here](https://github.com/victorsoares96/epubjs-react-native/tree/dev/example-bare/src/examples)

**Comment by divyanshkumarsharma** [comment]
It worked for me
