### ISSUE TITLE
Add option for continuous scrolling

### ISSUE THREAD

**Issue by hyfen** [victorsoares96/epubjs-react-native#54]
Great project! I'd love to have the option of rendering a book with continuous scrolling.

Is it as simple as passing `{method: "continuous"}` to the options in `renderTo()` [here](https://github.com/victorsoares96/epubjs-react-native/blob/dev/src/template.ts#L52)?

**Comment by Rama-Janani** [comment]
How to use after adding the method:"continuous" to the options  ??
