### ISSUE TITLE
onSelected not work in IOS

### ISSUE THREAD

**Issue by Ruslan-BG** [victorsoares96/epubjs-react-native#56]
onSelected not work in IOS ,but it work on Android

"react": "17.0.2",
 "react-native": "0.68.2",
 IOS 14.4

**Comment by victorsoares96** [comment]
#52 also reported this issue.. i will investigate this

**Comment by Ruslan-BG** [comment]
#52 [https://github.com/victorsoares96/epubjs-react-native/issues/52#issuecomment-1268116760](url)
