### ISSUE TITLE
epub fileopening  in ios emulator but not in real device 

### ISSUE THREAD

**Issue by Anubhavramos** [victorsoares96/epubjs-react-native#57]
the epub files are working fine in my ios emulator but only loading is showing in real devices.
Can someone please help regarding this

**Comment by victorsoares96** [comment]
some people related this issue.. i'll investigate this and try fix in the next version

**Comment by thuantvDr4** [comment]
same issue.

**Comment by toandev101** [comment]
How to workaround @victorsoares96 ?

**Comment by divyanshkumarsharma** [comment]
till when you can resolve this known bug ??? please take priority on this bug

**Comment by divyanshkumarsharma** [comment]
reply??

**Comment by MRizqyP** [comment]
same issue here.

**Comment by alex-dsbz** [comment]
Same issue here... It's blocking the Apple review of my customer's app...! Did anyone find a work around yet?

**Comment by siphu** [comment]
The issue seems to be when the ePub is trying to load the file locally after it downloads.
for those that don't really need the epub locally, you can use the following patch to allow the epub file to retain the remote URL -

```diff
diff --git a/node_modules/@epubjs-react-native/core/src/Reader.tsx b/node_modules/@epubjs-react-native/core/src/Reader.tsx
index c10f77e..f8d5266 100644
--- a/node_modules/@epubjs-react-native/core/src/Reader.tsx
+++ b/node_modules/@epubjs-react-native/core/src/Reader.tsx
@@ -82,7 +82,7 @@ export function Reader({
             throw new Error(`Invalid source name: ${src}`);
           }
 
-          if (sourceType === SourceType.OPF) {
+          if (sourceType === SourceType.OPF || sourceType === SourceType.EPUB) {
             setTemplate(
               injectBookVariables({
                 type: sourceType,
```

**Comment by MaganoAlan** [comment]
@siphu it works for me, thanks.

**Comment by DimuthuWeerathunga** [comment]
Guys i have found a way to fix this. this fix will allow epub files to be downloaded locally and read from local files, just as the author intended to write this library.

Changes to make:
1. download jszip and epubjs source code from the cdn and write them to the local files in the device's app's document dir. (you need to keep a reference to each of this uris which the the source code files are written and you will need to install the the expo-file-system module to the project, i think this is used under the hood by this guy's supporting file system library but i did not bother looking how to use his library to achieve this task, if you want further optimisations please go ahead and find how to use this guy's helper library)
please read steps below. after the changes the reader.tsx file should be like this

`
import React, { useContext, useEffect, useState } from 'react';
import * as FileSystem from 'expo-file-system';
import { FileSystemDownloadResult } from 'expo-file-system';
import { LoadingFile } from './utils/LoadingFile';
import type { ReaderProps } from './types';
import { View } from './View';
import { useInjectinjectWebviewVariables } from './hooks/useInjectWebviewVariables';
import { ReaderContext, defaultTheme as initialTheme } from './context';
import { isURL } from './utils/isURL';
import { getSourceType } from './utils/getSourceType';
import { getSourceName } from './utils/getPathname';
import { SourceType } from './utils/enums/source-type.enum';

// ...
export function Reader({
  src,
  width,
  height,
  defaultTheme = initialTheme,
  initialLocations,
  renderLoadingFileComponent = (props) => (
    <LoadingFile {...props} width={width} height={height} />
  ),
  fileSystem: useFileSystem,
  ...rest
}: ReaderProps) {
  const {
    downloadFile,
    size: fileSize,
    progress: downloadProgress,
    success: downloadSuccess,
    error: downloadError,
  } = useFileSystem();

  const { setIsLoading, isLoading } = useContext(ReaderContext);
  const { injectWebviewVariables } = useInjectinjectWebviewVariables();
  const [template, setTemplate] = useState<string | null>(null);
  const [templateUrl, setTemplateUrl] = useState<string | null>(null);
  const [allowedUris, setAllowedUris] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      setIsLoading(true);

      let jzipJsFileUri;
      let epubJsFileUri;

      const jzipDownloadResumable = FileSystem.createDownloadResumable(
        'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.5/jszip.min.js',
        FileSystem.documentDirectory + 'jszip.min.js',
        {},
        () => {}
      );

      try {
        jzipJsFileUri = ((await jzipDownloadResumable.downloadAsync()) as FileSystemDownloadResult)
          .uri;
      } catch (e) {
        throw new Error('failed to download jzip js file');
      }

      const epubjsDownloadResumable = FileSystem.createDownloadResumable(
        'https://cdn.jsdelivr.net/npm/epubjs/dist/epub.min.js',
        FileSystem.documentDirectory + 'epub.min.js',
        {},
        () => {}
      );

      try {
        epubJsFileUri = ((await epubjsDownloadResumable.downloadAsync()) as FileSystemDownloadResult)
          .uri;
      } catch (e) {
        throw new Error('failed to download epubjs js file');
      }

      if (src) {
        const sourceType = getSourceType(src);
        const isExternalSource = isURL(src);

        if (!sourceType) {
          throw new Error(`Invalid source type: ${src}`);
        }

        if (!isExternalSource) {
          if (sourceType === SourceType.BASE64) {
            setTemplate(
              injectWebviewVariables({
                jzipJs: jzipJsFileUri,
                epubJs: epubJsFileUri,
                type: SourceType.BASE64,
                book: src,
                theme: defaultTheme,
                locations: initialLocations,
                enableSelection: true,
              })
            );

            setIsLoading(false);
          } else {
            setTemplate(
              injectWebviewVariables({
                jzipJs: jzipJsFileUri,
                epubJs: epubJsFileUri,
                type: SourceType.BINARY,
                book: src,
                theme: defaultTheme,
                locations: initialLocations,
                enableSelection: true,
              })
            );

            setIsLoading(false);
          }
        }

        if (isExternalSource) {
          const sourceName = getSourceName(src);

          if (!sourceName) {
            throw new Error(`Invalid source name: ${src}`);
          }

          if (sourceType === SourceType.OPF) {
            setTemplate(
              injectWebviewVariables({
                jzipJs: jzipJsFileUri,
                epubJs: epubJsFileUri,
                type: sourceType,
                book: src,
                theme: defaultTheme,
                locations: initialLocations,
                enableSelection: true,
              })
            );

            setIsLoading(false);
          } else {
            let { uri: bookFileUri } = await downloadFile(src, sourceName);

            if (!bookFileUri) throw new Error("Couldn't download book");

            setAllowedUris(`${bookFileUri},${jzipJsFileUri},${epubJsFileUri}`);

            setTemplate(
              injectWebviewVariables({
                jzipJs: jzipJsFileUri,
                epubJs: epubJsFileUri,
                type: sourceType,
                book: bookFileUri,
                theme: defaultTheme,
                locations: initialLocations,
                enableSelection: true,
              })
            );

            setIsLoading(false);
          }
        }
      }
    })();
  }, [
    defaultTheme,
    downloadFile,
    initialLocations,
    injectWebviewVariables,
    setIsLoading,
    src,
  ]);

  useEffect(() => {
    const saveTemplateFileToDoc = async () => {
      try {
        if (template) {
          const content = template;

          const fileUri = FileSystem.documentDirectory + 'index.html';
          await FileSystem.writeAsStringAsync(fileUri, content);
          setTemplateUrl(fileUri);
        }
      } catch (error) {
        console.error('Error saving index.html file:', error);
        throw new Error('Error saving index.html file:');
      }
    };
    if (template) {
      saveTemplateFileToDoc();
    }
  }, [template]);

  if (isLoading) {
    return renderLoadingFileComponent({
      fileSize,
      downloadProgress,
      downloadSuccess,
      downloadError,
    });
  }

  if (!template) throw new Error('Template is not set');
  return (
    <View
      templateUri={templateUrl!}
      allowedUris={allowedUris!}
      width={width}
      height={height}
      {...rest}
    />
  );
}

`

2. change the template to include the placeholders for the downloaded jzip and epubjs. remove the cdn references.
`<script id="jzip"></script>
<script id="epubjs"></script>`


3. useInjectBookVariables hook is renamed to useInjectWebviewVariables, and include jzip and epubjs local uris to be injected in to the template. corrected code should look like below
`
import { useCallback } from 'react';
import type { Theme, ePubCfi } from '../types';
import template from '../template';
import type { SourceType } from '../utils/enums/source-type.enum';

export function useInjectinjectWebviewVariables() {
  const injectWebviewVariables = useCallback(
    ({
      jzipJs,
      epubJs,
      type,
      book,
      theme,
      enableSelection,
      locations,
    }: {
      jzipJs: string;
      epubJs: string;
      type: SourceType;
      book: string;
      theme: Theme;
      enableSelection: boolean;
      locations?: ePubCfi[];
    }) => {
      return template
        .replace(
          /<script id="jzip"><\/script>/,
          `<script src="${jzipJs}"></script>`
        )
        .replace(
          /<script id="epubjs"><\/script>/,
          `<script src="${epubJs}"></script>`
        )
        .replace(/const type = window.type;/, `const type = '${type}';`)
        .replace(/const file = window.book;/, `const file = '${book}';`)
        .replace(
          /const theme = window.theme;/,
          `const theme = ${JSON.stringify(theme)};`
        )
        .replace(
          /const initialLocations = window.locations;/,
          `const initialLocations = ${locations};`
        )
        .replace(
          /const enableSelection = window.enable_selection;/,
          `const enableSelection = ${enableSelection};`
        );
    },
    []
  );
  return { injectWebviewVariables };
}
`

4. in Reader.tsx add another use effect to save the template to app's local documents dir(a file named index.html). see code above

5. remove template and pass templateUrl and allowedUrls prop to the view component from the Reader.tsx file (the custom view this guy has made), and the allowedUris should be a comma separated string like this ``${bookFileUri},${jzipJsFileUri},${epubJsFileUri}``. again the code is above


6. In VIew.tsx  edit the prop type definition like this, 
`export type ViewProps = Omit<ReaderProps, 'src' | 'fileSystem'> & {
  templateUri: string;
  allowedUris: string;
};`
and change the accepted props to reflect the change,
`
export function View({
  templateUri,
  allowedUris,
  onStarted = () => {},
  onReady = () => {},
  onDisplayError = () => {},
  onResized = () => {},
  onLocationChange = () => {},
  onRendered = () => {},
  onSearch = () => {},
  onLocationsReady = () => {},
  onSelected = () => {},
  onMarkPressed = () => {},
  onOrientationChange = () => {},
  onLayout = () => {},
  onNavigationLoaded = () => {},
  onBeginning = () => {},
  onFinish = () => {},
  onPress = () => {},
  onDoublePress = () => {},
  width,
  height,
  initialLocation,
  enableSwipe = true,
  onSwipeLeft = () => {},
  onSwipeRight = () => {},
  defaultTheme = initialTheme,
  renderOpeningBookComponent = () => (
    <OpeningBook width={width} height={height} />
  ),
}: ViewProps) 
`

7. on the WebView component edit the source prop like this `source={{ uri: templateUri }}`,
and add this prop to that also `allowingReadAccessToURL={allowedUris}`


I'm gonna create a pull request and mention this issue, I dont know this will be merged or not so I'll link the fork here
https://github.com/DimuthuWeerathunga/epubjs-react-native

**Comment by DimuthuWeerathunga** [comment]
https://github.com/victorsoares96/epubjs-react-native/pull/107

**Comment by DimuthuWeerathunga** [comment]
exact commit that fixes this d852f2ad7a9fc982c52d60afc58b4d4c303a582e

**Comment by sam-ruby** [comment]
I am having issues making this work in a Bare react native project.  1.3 has a dependency on expo file system and writing to this file system is throwing an error. I am not clear, what's the purpose of "useFileSystem" property passed , which appears to be not used here. Looking at the documentation for expo-file-system - https://github.com/expo/expo/tree/main/packages/expo-file-system#installation-in-bare-react-native-projects - , it says to install expo package first. Not sure why I need expo to be installed if this is going to be running in bare react native project. Just commenting here, in case any one runs into this issue.

**Comment by David-Liu-8872** [comment]
Still seeing the issue atm. Trying to open .epub file IOS, works fine on simulator but stuck at Loading 0% in real device

Versions:
    "@epubjs-react-native/core": "^1.3.0",
    "@epubjs-react-native/file-system": "^1.1.2",
    "react-native": "0.73.5",

**Comment by dcallus** [comment]
I am also getting this :(
If I do this when loading the file
`const result = await getDocumentAsync({
			type: 'application/epub+zip',
			copyToCacheDirectory: Platform.OS === 'android'
		});`
		
it helps a lot, but it still sometimes fails when reloading a book by navigating back to the library and then bak again

**Comment by victorsoares96** [comment]
@dcallus you need to pass the `copyToCacheDirectory ` parameter as mentioned, unfortunately this is the only way to load the book so far

**Comment by dcallus** [comment]
> copyToCacheDirectory

This doesn't work for me unfortunately. I'm on iOS so the above should have been false anyway. But I checked with false anyway and it still doesn't work :(

**Comment by dcallus** [comment]
Update: I've figured out that 99% of the time (or more), I can't open a file I've loaded after exactly 1 minute. 59 seconds is fine.

My code has no reference to anything to do with time.

**Comment by dcallus** [comment]
further info on this bug, although I seem to have a solution.
When the book is stuck on an infinite load (after 60 seconds), if I swipe to turn a page it says in an alert
`undefined is not an object (evaluating 'this.manager.next')`
