### ISSUE TITLE
highlight the search result

### ISSUE THREAD

**Issue by PrakharDT** [victorsoares96/epubjs-react-native#59]
is there any option to highlight the search results after searching the words in book using readerProvider?

**Comment by natesanyo** [comment]
I highlight search terms by using the following render method for your FlatList component items where you display the search results...
`const renderSearchItem = ({ item }) => {
    const regex = new RegExp(`(${searchTerm})`, "gi");
    const parts = item.excerpt.split(regex);

    return (
      <View>
        <AppText
          style={styles.itemMain}
          onPress={() => {
            goToLocation(item.cfi);
            toggleSearchModal();
          }}
        >
          {parts.filter(String).map((part, i) => {
            return regex.test(part) ? (
              <AppText style={styles.highlight} key={i}>
                {part}
              </AppText>
            ) : (
              <AppText key={i}>{part}</AppText>
            );
          })}
        </AppText>
      </View>
    );
  };`

**Comment by Rama-Janani** [comment]
how to highlight inside the book ?

**Comment by victorsoares96** [comment]
> how to highlight inside the book ?

@Rama-Janani I added a new annotation API that could help you with your problem, take a look at this related pull request!

**Comment by victorsoares96** [comment]
thanks @natesanyo for the code!

I will close this issue, if the author needs it he can reopen it
