### ISSUE TITLE
File format question

### ISSUE THREAD

**Issue by saifmattias** [victorsoares96/epubjs-react-native#6]
Hello, 

I am trying to make it work with .epub file format, but it is not working. Is there any limitation in this package for which file format it allow? I can see from your example you are using only .opf, does this mean .epub will not work?

Thanks for this amazing work!

**Comment by fabiancarlos** [comment]
i respond that here #7

**Comment by victorsoares96** [comment]
hi @saifmattias, i solving this issue in next version wich be released soon
