### ISSUE TITLE
How to prevent user of copying any text in file?

### ISSUE THREAD

**Issue by M-HARIS-97** [victorsoares96/epubjs-react-native#62]
How to prevent user of copying any text in file?

<img width="274" alt="Screenshot 2022-10-18 at 12 27 41 PM" src="https://user-images.githubusercontent.com/57429370/196358101-bc16e074-aea4-418e-8e2e-a79d0755ee76.png">

**Comment by shreyas-tarento** [comment]
@M-HARIS-97 
` <ReaderProvider>
        <Reader
          src="https://s3.amazonaws.com/moby-dick/OPS/package.opf"
          width={width}
          height={height}
          fileSystem={useFileSystem}
          defaultTheme={{
            body: {
              **'-moz-user-select': 'none',
              '-webkit-user-select': 'none',
              '-ms-user-select': 'none',
              'user-select': 'none',
              '-o-user-select': 'none',**
            },
          }}
        />
      </ReaderProvider>`

**Comment by victorsoares96** [comment]
You can use the prop enableSelection as `false` such this:

OBS: This prop not working before the v1.4.0 
```tsx
<ReaderProvider>
  <Reader
   src="https://s3.amazonaws.com/moby-dick/OPS/package.opf"
   width={width}
   height={height}
   fileSystem={useFileSystem}
   enableSelection={false}
  />
</ReaderProvider>
```
