### ISSUE TITLE
save the last page as state

### ISSUE THREAD

**Issue by D3troit98** [victorsoares96/epubjs-react-native#63]
How do I get the current location, or where I am and save the state... so as to resume from that initial location when I load the book again

**Comment by D3troit98** [comment]
Epubs are nice. But it kinda takes the fun away if one can't continue from where they stop. And can would you please also show me how to use the hooks

**Comment by D3troit98** [comment]
I've figured out how to use the hook state. Took some time. Your project is amazing

**Comment by PrakharDT** [comment]
could you please upload your source code.
Thanks in advance

**Comment by D3troit98** [comment]
Okay. I can just send you the GitHub link. Please star it. I'm still working on it, but I've fixed the location issue

**Comment by PrakharDT** [comment]
> Okay. I can just send you the GitHub link. Please star it. I'm still working on it, but I've fixed the location issue

@D3troit98 Please Share the link.

**Comment by D3troit98** [comment]
https://github.com/D3troit98/Ebook_Reader
