### ISSUE TITLE
Bookmark and Highlight

### ISSUE THREAD

**Issue by Pelema** [victorsoares96/epubjs-react-native#66]
Hi I'm trying to add bookmarks and highlights, haven't made any progress and there's example can you please assist

**Comment by victorsoares96** [comment]
@Pelema I added a new annotation API that could help you with your problem, take a look at this related pull request!

Note: about bookmarks, I'm still working on it, but it will be out in the next few days...

**Comment by victorsoares96** [comment]
all done @Pelema! check the examples folder within the repository for more details on how to use bookmarks

**Comment by ayushgupta-1** [comment]
Is there an option to preload the bookmark after the book loads via AsyncStorage, considering we save the location object to AsyncStorage, retrieve it on app mount, pass the location object to the addBookmark hook.

Unexpectedly it's not working, and I'm seeing nothing being logged via Reader Params onAddBookmark

Passing the location object to addBookmark hook should do the trick right ?
