### ISSUE TITLE
getLocations method always returns an empty array

### ISSUE THREAD

**Issue by sem-aa** [victorsoares96/epubjs-react-native#68]
I need to get an array of all locations in order to make a clickable table of contents for the book. At the moment, I can only get the current location, how can I get all the locations in one array from the book.

**Comment by machiAkram** [comment]
Same. It seems that the OnLocationsReady event is called before the book.locations.generate() function has completed. This is why the locations array is empty and totalLocations is not accurate. I think it needs to be wrapped in a .then() bloc.

@victorsoares96 maybe you could look into this

**Comment by siphu** [comment]
Had similar issue. Made a simple patch using patch-package.

```
diff --git a/node_modules/@epubjs-react-native/core/src/template.ts b/node_modules/@epubjs-react-native/core/src/template.ts
index bb97d30..1c1b065 100644
--- a/node_modules/@epubjs-react-native/core/src/template.ts
+++ b/node_modules/@epubjs-react-native/core/src/template.ts
@@ -57,10 +57,10 @@ export default `
       window.ReactNativeWebView.postMessage(JSON.stringify({ type: "onStarted" }));
 
       book.ready
-        .then(function () {
+        .then(async function () {
           if (initialLocations) {
             book.locations.load(initialLocations);
-          } else book.locations.generate(1600);
+          } else await book.locations.generate(1600);
 
           var displayed = rendition.display();
 
```

Also, the TOC is passed through the method `onNavigationLoaded` which is not listed in the readme.

**Comment by D3troit98** [comment]
This works. This should be added @victorsoares96

**Comment by D3troit98** [comment]
> Had similar issue. Made a simple patch using patch-package.
> 
> ```diff
> diff --git a/node_modules/@epubjs-react-native/core/src/template.ts b/node_modules/@epubjs-react-native/core/src/template.ts
> index bb97d30..1c1b065 100644
> --- a/node_modules/@epubjs-react-native/core/src/template.ts
> +++ b/node_modules/@epubjs-react-native/core/src/template.ts
> @@ -57,10 +57,10 @@ export default `
>        window.ReactNativeWebView.postMessage(JSON.stringify({ type: "onStarted" }));
>  
>        book.ready
> -        .then(function () {
> +        .then(async function () {
>            if (initialLocations) {
>              book.locations.load(initialLocations);
> -          } else book.locations.generate(1600);
> +          } else await book.locations.generate(1600);
>  
>            var displayed = rendition.display();
>  
> ```
> 
> Also, the TOC is passed through the method `onNavigationLoaded` which is not listed in the readme.

how do you use the onNavigationLoaded

**Comment by siphu** [comment]
`onNavigationLoaded` sends back an array of of locations that i called Chapter

```ts
interface Chapter {
  label: string;
  id: string;
  href: string;
  subitems: Array<Chapter>;
  parent?: string;
}


onNavigationLoaded={(chapters: Array<Chapter>) => {

}}
```

from there, you can use the `goToLocation` method to jump to the location via the href property.

```ts
  const BookReader = useReader();
  ...
  BookReader.goToLocation(chapter.href);
```

**Comment by hifreaker** [comment]
> `onNavigationLoaded` sends back an array of of locations inside a property called `toc` that i called Chapter
> 
> ```ts
> interface Chapter {
>   label: string;
>   id: string;
>   href: string;
>   subitems: Array<Chapter>;
>   parent?: string;
> }
> 
> 
> onNavigationLoaded={toc => {
>  const chapters = (toc.toc || []) as Array<Chapter>;
> }}
> ```
> 
> from there, you can use the `goToLocation` method to jump to the location via the href property.
> 
> ```ts
>   const BookReader = useReader();
>   ...
>   BookReader.goToLocation(chapter.href);
> ```

How do you use onNavigationLoaded?

**Comment by sem-aa** [comment]
> Had similar issue. Made a simple patch using patch-package.
> 
> ```diff
> diff --git a/node_modules/@epubjs-react-native/core/src/template.ts b/node_modules/@epubjs-react-native/core/src/template.ts
> index bb97d30..1c1b065 100644
> --- a/node_modules/@epubjs-react-native/core/src/template.ts
> +++ b/node_modules/@epubjs-react-native/core/src/template.ts
> @@ -57,10 +57,10 @@ export default `
>        window.ReactNativeWebView.postMessage(JSON.stringify({ type: "onStarted" }));
>  
>        book.ready
> -        .then(function () {
> +        .then(async function () {
>            if (initialLocations) {
>              book.locations.load(initialLocations);
> -          } else book.locations.generate(1600);
> +          } else await book.locations.generate(1600);
>  
>            var displayed = rendition.display();
>  
> ```
> 
> Also, the TOC is passed through the method `onNavigationLoaded` which is not listed in the readme.

when I add this patch the book takes much longer to open. Maybe there is some other way to force all the information to be loaded along with the opening of the book
