### ISSUE TITLE
How can I get metadata for an epub?

### ISSUE THREAD

**Issue by Jemeni11** [victorsoares96/epubjs-react-native#69]
I want to get basic stuff like the author's name, publisher, description, etc. Is there any way of doing this???

**Comment by Anton-Kravkenko** [comment]
Hey, in you project work useReader hook?

**Comment by Anton-Kravkenko** [comment]
Mee too needed metadata

**Comment by Jemeni11** [comment]
> Hey, in you project work useReader hook?

No I am not

**Comment by D3troit98** [comment]
Anyone figured a way on this? Or should we have to edit the code

**Comment by D3troit98** [comment]
Anyone figured a way on this? Or should we have to edit the code

**Comment by siphu** [comment]
You'll have to edit the template or patch the default template to get the meta data.
inside the `book.ready`, you can add something like -
```typescript
window.ReactNativeWebView.postMessage(JSON.stringify({ type: "meta", data: book.package.metadata }));
```

if you want to get the book cover, then you'll have to be more creative by -
1. reading the url through book.coverUrl()
2. converting it to a blob
3. using FileReader to convert it into a base64.

**Comment by Anton-Kravkenko** [comment]
Oh my good, you know any complete case for example?

**Comment by Jemeni11** [comment]
> You'll have to edit the template or patch the default template to get the meta data. inside the `book.ready`, you can add something like -
> 
> ```ts
> window.ReactNativeWebView.postMessage(JSON.stringify({ type: "meta", data: book.package.metadata }));
> ```
> 
> you'll also have to patch the `View.tsx` to also pass that data back to wherever you want to use it.
> 
> if you want to get the book cover, then you'll have to be more creative by -
> 
> 1. reading the url through book.coverUrl()
> 2. converting it to a blob
> 3. using FileReader to convert it into a base64.


Thanks !!!
I did this and it works.
Unfortunately, the book.coverUrl() doesn't work. It returns an empty object `Object{}`

**Comment by siphu** [comment]
@Jemeni11 
this is what how I did it -
```typescript
const meta = book.package.metadata;
book.coverUrl().then(async (url) => {
    var reader = new FileReader();
    reader.onload = (res) => { 
        window.ReactNativeWebView.postMessage(JSON.stringify({ type: "cover", cover: reader.result, meta: meta }));
    }
    reader.readAsDataURL(await fetch(url).then(res => res.blob()));
  }).catch(()=>{
    window.ReactNativeWebView.postMessage(JSON.stringify({ type: "cover", cover: undefined, meta: meta }));
  });
```

**Comment by Jemeni11** [comment]
Once again, thanks !!! This worked!!

I made a pull request: https://github.com/victorsoares96/epubjs-react-native/pull/73

**Comment by Anton-Kravkenko** [comment]
How can I get the metadata for a book that the user won't open?

**Comment by Jemeni11** [comment]
> How can I get the metadata for a book that the user won't open?
> for example the user hasn't opened the book and how can I get the book's metadata right away. It is also interesting whether it is possible to make the translation functionality of the book?

I do not know how to do this with this library but you can use [xmldom](https://github.com/xmldom/xmldom) and do something like this:
```javascript
const { DOMParser } = require("@xmldom/xmldom");

let xmlMetadata;

export async function parseXML(xmlFile) {
  try {
    const response = await fetch(xmlFile);
    const xmlText = await response.text();
    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(xmlText, "application/xml");  // "application/xml" or "text/xml"

    xmlMetadata = {
      title: xmlDoc.getElementsByTagName("dc:title")[0].textContent,
      author: xmlDoc.getElementsByTagName("dc:creator")[0].textContent,
      date: xmlDoc.getElementsByTagName("dc:publisher")[0].textContent,
    };
    return xmlMetadata;
  } catch (error) {
    console.error(`Error parsing XML: ${error}`);
  }
}
```
where `xmlFile` is the path to the `.opf file` of the epub. 

Of course you'll need to unzip the epub to even get to the `.opf file` in the first place and I don't know how to do that.

**Comment by Jemeni11** [comment]
> and how can you do offline reading guys?

I ... did not notice this. Are you saying this library only works if there's an internet connection?

**Comment by Jemeni11** [comment]
> Of course you'll need to unzip the epub to even get to the `.opf file` in the first place and I don't know how to do that.

UPDATE:
You can use any of these libraries:
- [Epub-ocf](https://github.com/glkz/epub-ocf)
- [Adm-zip](https://www.npmjs.com/package/adm-zip)
- [JSZip](https://stuk.github.io/jszip/documentation/examples.html)

You'll have to read the docs because I only skimmed through but from what I saw they should work. 

I even [tested JSZip](https://stuk.github.io/jszip/documentation/examples/read-local-file-api.html) and it printed out the correct output

![Screenshot](https://raw.githubusercontent.com/Jemeni11/hosting-pics/main/Reading-a-local-file-with-the-File-API.png)

**Comment by Anton-Kravkenko** [comment]
I tried these three libraries but they either do not work with react native expo or they are long out of date, can you please show me an example code that could unzip epub like on JSZip site?
Thank you very much and sorry, I am new to react native

**Comment by Jemeni11** [comment]
> I tried these three libraries but they either do not work with react native expo or they are long out of date, can you please show me an example code that could unzip epub like on JSZip site? Thank you very much and sorry, I am new to react native
> 
> > > Of course you'll need to unzip the epub to even get to the `.opf file` in the first place and I don't know how to do that.
> > 
> > 
> > UPDATE: You can use any of these libraries:
> > 
> > * [Epub-ocf](https://github.com/glkz/epub-ocf)
> > * [Adm-zip](https://www.npmjs.com/package/adm-zip)
> > * [JSZip](https://stuk.github.io/jszip/documentation/examples.html)
> > 
> > You'll have to read the docs because I only skimmed through but from what I saw they should work.
> > I even [tested JSZip](https://stuk.github.io/jszip/documentation/examples/read-local-file-api.html) and it printed out the correct output
> > ![Screenshot](https://raw.githubusercontent.com/Jemeni11/hosting-pics/main/Reading-a-local-file-with-the-File-API.png)

Hey @Anton-Kravkenko 
I made an app using JSZip and Expo
Here's the repo: https://github.com/Jemeni11/ePub-file-details
When an ePub is selected, the app lists out all the files in the epub.

**Comment by Anton-Kravkenko** [comment]
Oh my good, thank you

**Comment by Anton-Kravkenko** [comment]
I fixed the problem of difference epub files and missing components using google book api, title is in all, with it I did it. There is no other choice, almost all applications for reading books use this approach
