### ISSUE TITLE
File format

### ISSUE THREAD

**Issue by rauleffting** [victorsoares96/epubjs-react-native#7]
The package is reading just the opf format. How to read an epub insid de app?

**Comment by fabiancarlos** [comment]
Download the file on the storage device, than read and convert to base64, using a lib called `rn-fetch-blob`, could do that.

**Comment by OlgaSavit** [comment]
> Download the file on the storage device, than read and convert to base64, using a lib called `rn-fetch-blob`, could do that.
it didn't work for me
convert the file https://s3.amazonaws.com/moby-dick/OPS/package.opf (for example) to base64 ->
PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHBhY2thZ2UgeG1sbnM9Imh0dHA6Ly93d3cuaWRwZi5vcmcvMjAwNy9vcGYiIHZlcnNpb249IjMuMCIgeG1sOmxhbmc9ImVuIiB1bmlxdWUtaWRlbnRpZmllcj0icHViLWlkIiBwcmVmaXg9ImNjOiBodHRwOi8vY3JlYXRpdmVjb21tb25zLm9yZy9ucyMiPgogIDxtZXRhZGF0YSB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iPgogICAgPGRjOnRpdGxlIGlkPSJ0aXRsZSI+TW9ieS1EaWNrPC9kYzp0aXRsZT4KICAgIDxtZXRhIHJlZmluZXM9IiN0aXRsZSIgcHJvcGVydHk9InRpdGxlLXR5cGUiPm1haW48L21ldGE+CiAgICA8ZGM6Y3JlYXRvciBpZD0iY3JlYXRvciI+SGVybWFuIE1lbHZpbGxlPC9kYzpjcmVhdG9yPgogICAgPG1ldGEgcmVmaW5lcz0iI2NyZWF0b3IiIHByb3BlcnR5PSJmaWxlLWFzIj5NRUxWSUxMRSwgSEVSTUFOPC9tZXRhPgogICAgPG1ldGEgcmVmaW5lcz0iI2NyZWF0b3IiIHByb3BlcnR5PSJyb2xlIiBzY2hlbWU9Im1hcmM6cmVsYXRvcnMiPmF1dDwvbWV0YT4KICAgIDxkYzppZGVudGlmaWVyIGlkPSJwdWItaWQiPmNvZGUuZ29vZ2xlLmNvbS5lcHViLXNhbXBsZXMubW9ieS1kaWNrLWJhc2ljPC9kYzppZGVudGlmaWVyPgogICAgPGRjOmxhbmd1YWdlPmVuLVVTPC9kYzpsYW5ndWFnZT4KICAgIDxtZXRhIHByb3BlcnR5PSJkY3Rlcm1zOm1vZGlmaWVkIj4yMDEyLTAxLTE4VDEyOjQ3OjAwWjwvbWV 0YT4KICAgIDxkYzpwdWJsaXNoZXI+SGFycGVyICZhbXA7IEJyb3RoZXJzLCBQdWJsaXNoZXJzPC9kYzpwdWJsaXNoZXI+CiAgICA8ZGM6Y29udHJpYnV0b3IgaWQ9ImNvbnRyaWIxIj5EYXZlIENyYW1lcjwvZGM6Y29udHJpYnV0b3I+CiAgICA8bWV0YSByZWZpbmVzPSIjY29udHJpYjEiIHByb3BlcnR5PSJyb2xlIiBzY2hlbWU9Im1hcmM6cmVsYXRvcnMiPm1yazwvbWV0YT4KICAgIDxkYzpyaWdodHM+VGhpcyB3b3JrIGlzIHNoYXJlZCB3aXRoIHRoZSBwdWJsaWMgdXNpbmcgdGhlIEF0dHJpYnV0aW9uLVNoYXJlQWxpa2UgMy4wIFVucG9ydGVkIChDQyBCWS1TQSAzLjApIGxpY2Vuc2UuPC9kYzpyaWdodHM+ICAgICAgICAKICAgIDxsaW5rIHJlbD0iY2M6bGljZW5zZSIgaHJlZj0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbGljZW5zZXMvYnktc2EvMy4wLyIvPgogICAgPG1ldGEgcHJvcGVydHk9ImNjOmF0dHJpYnV0aW9uVVJMIj5odHRwOi8vY29kZS5nb29nbGUuY29tL3AvZXB1Yi1zYW1wbGVzLzwvbWV0YT4KICA8L21ldGFkYXRhPgogIDxtYW5pZmVzdD4KICAgIDxpdGVtIGlkPSJuY3h0b2MiIG1lZGlhLXR5cGU9ImFwcGxpY2F0aW9uL3gtZHRibmN4K3htbCIgaHJlZj0idG9jLm5jeCIvPgogICAgPGl0ZW0gaWQ9ImZvbnQuc3RpeC5yZWd1bGFyIiBocmVmPSJmb250cy9TVElYR2VuZXJhbC5vdGYiCiAgICAgIG1lZGlhLXR5cGU9ImFwcGxpY2F0aW9uL3ZuZC5tcy1vcGVudHlwZSIvPgogICAgPGl0ZW0gaWQ 9ImZvbnQuc3RpeC5pdGFsaWMiIGhyZWY9ImZvbnRzL1NUSVhHZW5lcmFsSXRhbGljLm90ZiIKICAgICAgbWVkaWEtdHlwZT0iYXBwbGljYXRpb24vdm5kLm1zLW9wZW50eXBlIi8+CiAgICA8aXRlbSBpZD0iZm9udC5zdGl4LmJvbGQiIGhyZWY9ImZvbnRzL1NUSVhHZW5lcmFsQm9sLm90ZiIKICAgICAgbWVkaWEtdHlwZT0iYXBwbGljYXRpb24vdm5kLm1zLW9wZW50eXBlIi8+CiAgICA8aXRlbSBpZD0iZm9udC5zdGl4LmJvbGQuaXRhbGljIiBocmVmPSJmb250cy9TVElYR2VuZXJhbEJvbEl0YS5vdGYiCiAgICAgIG1lZGlhLXR5cGU9ImFwcGxpY2F0aW9uL3ZuZC5tcy1vcGVudHlwZSIvPgogICAgPGl0ZW0gaWQ9InRvYyIgcHJvcGVydGllcz0ibmF2IiBocmVmPSJ0b2MueGh0bWwiIG1lZGlhLXR5cGU9ImFwcGxpY2F0aW9uL3hodG1sK3htbCIvPgogICAgPGl0ZW0gaWQ9ImNvcHlyaWdodCIgaHJlZj0iY29weXJpZ2h0LnhodG1sIiBtZWRpYS10eXBlPSJhcHBsaWNhdGlvbi94aHRtbCt4bWwiLz4KICAgIDxpdGVtIGlkPSJ0aXRsZXBhZ2UiIGhyZWY9InRpdGxlcGFnZS54aHRtbCIgbWVkaWEtdHlwZT0iYXBwbGljYXRpb24veGh0bWwreG1sIi8+CiAgICA8aXRlbSBpZD0iY292ZXIiIGhyZWY9ImNvdmVyLnhodG1sIiBtZWRpYS10eXBlPSJhcHBsaWNhdGlvbi94aHRtbCt4bWwiLz4KICAgIDxpdGVtIGlkPSJjb3Zlci1pbWFnZSIgcHJvcGVydGllcz0iY292ZXItaW1hZ2UiIGhyZWY9ImltYWdlcy85NzgwMzE2MDAwMDA wLmpwZyIKICAgICAgbWVkaWEtdHlwZT0iaW1hZ2UvanBlZyIvPgogICAgPGl0ZW0gaWQ9InN0eWxlIiBocmVmPSJjc3Mvc3R5bGVzaGVldC5jc3MiIG1lZGlhLXR5cGU9InRleHQvY3NzIi8+CiAgICA8aXRlbSBpZD0iYU1vYnktRGlja19GRV90aXRsZV9wYWdlIiBocmVmPSJpbWFnZXMvTW9ieS1EaWNrX0ZFX3RpdGxlX3BhZ2UuanBnIgogICAgICBtZWRpYS10eXBlPSJpbWFnZS9qcGVnIi8+CiAgICA8aXRlbSBpZD0ieHByZWZhY2VfMDAxIiBocmVmPSJwcmVmYWNlXzAwMS54aHRtbCIgbWVkaWEtdHlwZT0iYXBwbGljYXRpb24veGh0bWwreG1sIi8+CiAgICA8aXRlbSBpZD0ieGludHJvZHVjdGlvbl8wMDEiIGhyZWY9ImludHJvZHVjdGlvbl8wMDEueGh0bWwiIG1lZGlhLXR5cGU9ImFwcGxpY2F0aW9uL3hodG1sK3htbCIvPgogICAgPGl0ZW0gaWQ9InhlcGlncmFwaF8wMDEiIGhyZWY9ImVwaWdyYXBoXzAwMS54aHRtbCIgbWVkaWEtdHlwZT0iYXBwbGljYXRpb24veGh0bWwreG1sIi8+CiAgICA8aXRlbSBpZD0ieGNoYXB0ZXJfMDAxIiBocmVmPSJjaGFwdGVyXzAwMS54aHRtbCIgbWVkaWEtdHlwZT0iYXBwbGljYXRpb24veGh0bWwreG1sIi8+CiAgICA8aXRlbSBpZD0ieGNoYXB0ZXJfMDAyIiBocmVmPSJjaGFwdGVyXzAwMi54aHRtbCIgbWVkaWEtdHlwZT0iYXBwbGljYXRpb24veGh0bWwreG1sIi8+CiAgICA8aXRlbSBpZD0ieGNoYXB0ZXJfMDAzIiBocmVmPSJjaGFwdGVyXzAwMy54aHRtbCIgbWVkaWEtdHlwZT0 iYXBwbGljYXRpb24veGh0bWwreG1sIi8+CiAgICA8aXRlbSBpZD0ieGNoYXB0ZXJfMDA0IiBocmVmPSJjaGFwdGVyXzAwNC54aHRtbCIgbWVkaWEtdHlwZT0iYXBwbGljYXRpb24veGh0bWwreG1sIi8+CiAgICA8aXRlbSBpZD0ieGNoYXB0ZXJfMDA1IiBocmVmPSJjaGFwdGVyXzAwNS54aHRtbCIgbWVkaWEtdHlwZT0iYXBwbGljYXRpb24veGh0bWwreG1sIi8+CiAgICA8aXRlbSBpZD0ieGNoYXB0ZXJfMDA2IiBocmVmPSJjaGFwdGVyXzAwNi54aHRtbCIgbWVkaWEtdHlwZT0iYXBwbGljYXRpb24veGh0bWwreG1sIi8+CiAgICA8aXRlbSBpZD0ieGNoYXB0ZXJfMDA3IiBocmVmPSJjaGFwdGVyXzAwNy54aHRtbCIgbWVkaWEtdHlwZT0iYXBwbGljYXRpb24veGh0bWwreG1sIi8+CiAgICA8aXRlbSBpZD0ieGNoYXB0ZXJfMDA4IiBocmVmPSJjaGFwdGVyXzAwOC54aHRtbCIgbWVkaWEtdHlwZT0iYXBwbGljYXRpb24veGh0bWwreG1sIi8+CiAgICA8aXRlbSBpZD0ieGNoYXB0ZXJfMDA5IiBocmVmPSJjaGFwdGVyXzAwOS54aHRtbCIgbWVkaWEtdHlwZT0iYXBwbGljYXRpb24veGh0bWwreG1sIi8+CiAgICA8aXRlbSBpZD0ieGNoYXB0ZXJfMDEwIiBocmVmPSJjaGFwdGVyXzAxMC54aHRtbCIgbWVkaWEtdHlwZT0iYXBwbGljYXRpb24veGh0bWwreG1sIi8+CiAgICA8
 <Reader
        onLocationsReady={setLocations}
        onLocationChange={setActiveLocation}
        onNavigationLoaded={setToc}
        onStarted={() => setLoader(true)}
        onReady={() => {
          setLoader(false);
        }}
        // src={{uri: 'https://s3.amazonaws.com/moby-dick/OPS/package.opf'}}
        src={{
          base64: base64
        }}
        onDisplayError={err => console.log('err', err)}
        isLoading={<Text>ee</Text>}
        width={width}
        height={height}
        progress={true}
        defaultTheme={darkTheme}
        initialLocation={activeLocation}
      />
      the book is not displayed, there are no errors in the console
      What is my mistake?

**Comment by victorsoares96** [comment]
hi guys, i solving this issue in next version, sorry for answering soo late..

**Comment by rashidwiizb** [comment]
@OlgaSavit is the OPF to Base64 conversion issue resolved, and can the resulting Base64 file be read as expected?
