### ISSUE TITLE
isUrl passed when base64 String contains http (is most off cases it could) the it's throw error "Invalid Url"

### ISSUE THREAD

**Issue by wreyw213** [victorsoares96/epubjs-react-native#72]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@epubjs-react-native/core@1.1.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@epubjs-react-native/core/src/utils/isURL.ts b/node_modules/@epubjs-react-native/core/src/utils/isURL.ts
index 336fd97..23f7ba2 100644
--- a/node_modules/@epubjs-react-native/core/src/utils/isURL.ts
+++ b/node_modules/@epubjs-react-native/core/src/utils/isURL.ts
@@ -1,3 +1,3 @@
 export function isURL(value: string) {
-  return value.includes('http');
+  return value.includes('https://');
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by victorsoares96** [comment]
Thanks for the help, I added a fix for this in the latest versions of the library
