### ISSUE TITLE
Cannot set any useState inside Onselected.

### ISSUE THREAD

**Issue by abhishekv-gloify** [victorsoares96/epubjs-react-native#74]
I am using this code to set usestate ,but error is coming.
when i am selecting the text it show me this error.
error : template is not set.

const Dictionary = () => {
  const [data, setData] = useState('hello');
  const {width, height} = useWindowDimensions();
  const [searched, setSearched] = useState();

  const SetupDta = () => {
    const {addMark, getCurrentLocation, goNext, getLocations} = useReader();
    const [modalVisible, setModalVisible] = useState(false);
    const refRBSheet = useRef();
    console.log('data', data);
    return (
      <View>
        <Reader
          src="https://s3.amazonaws.com/moby-dick/OPS/package.opf"
          width={width}
          height={height}
          fileSystem={useFileSystem}
          onSelected={text => {
            setSearched(text);
          }}
          onMarkPressed={text => {
            console.log('marked', text);
          }}
        />
      </View>
    );
  };

  return (
    <ReaderProvider>
      <SetupDta />
    </ReaderProvider>
  );
};

export default Dictionary;

**Comment by victorsoares96** [comment]
Are you still having this problem? What version of the library are you using?
