### ISSUE TITLE
translation, getting metadata without opening, offline reading

### ISSUE THREAD

**Issue by kravchenko-anton** [victorsoares96/epubjs-react-native#76]
How can I get the metadata for a book that the user won't open?
for example the user hasn't opened the book and how can I get the book's metadata right away. It is also interesting whether it is possible to make the translation functionality of the book?
and how can you do offline reading guys?

**Comment by Ruslan-BG** [comment]
Оффлайна нету! Вы должный его сами реализовать

**Comment by Anton-Kravkenko** [comment]
Do you have an example?

> Оффлайна нету! Вы должный его сами реализовать :)

**Comment by SamuelPremji** [comment]
> Do you have an example?
> 
> > Оффлайна нету! Вы должный его сами реализовать :)

How do you even get metadata in the first place?
