### ISSUE TITLE
Loading always show at 0%

### ISSUE THREAD

**Issue by wolfwithcode** [victorsoares96/epubjs-react-native#79]

**Comment by wolfwithcode** [comment]
I fixed it! Thanks!

**Comment by D3troit98** [comment]
probably because of your wrong src file

**Comment by vishal27shenoy** [comment]
how did you fix that ?

**Comment by victorsoares96** [comment]
@vishal27shenoy take a look at the examples provided in the repository, maybe they can help you

**Comment by victorsoares96** [comment]
I will be closing this issue, if necessary the author can reopen it
