### ISSUE TITLE
cant open local file , just the one in the example. probably only from web

### ISSUE THREAD

**Issue by eyalgromzin** [victorsoares96/epubjs-react-native#8]
i was able to open the example . 
but couldnt load a local file . how can i do that ?

**Comment by fabiancarlos** [comment]
You can do it by get a epub file from a API, download and saving on the device, get the path and read using someting like RNFetchBlob, then convert to a base64, and use on the Book component, the final result on the provider is something like this:

`
<Book
  dataBase64={yourDataBase64}
/>
`

**Comment by anacchaves** [comment]
I'm ok all through steps 1-3 using FyleSystem.readAsString to make base64 conversion instead of RNfetchBlob(should work the same), but when i assign the variable to reader src it still doesn't work :(

**Comment by anacchaves** [comment]
update: everything is working just fine :} I was having issues related to memory management that were unrelated to this library. 
For anyone wondering: 
1. Once you have your file locally you need to access this file using some file management lib (RNFetchBlob, expo File System etc - any of these should have the methods you need)
2. Then you need to read this file encoding it do base64 and storing this string to a variable (both libraries cited have the methods to do this). Here you need to be careful with memory management - I was storing this *huge* string on RAM and it was breaking everything.
3. Pass the string to Reader as `src = {{ base64: variableContainingBase64String }}`

**Comment by csmattila** [comment]
> update: everything is working just fine :} I was having issues related to memory management that were unrelated to this library. For anyone wondering:
> 
>     1. Once you have your file locally you need to access this file using some file management lib (RNFetchBlob, expo File System etc - any of these should have the methods you need)
> 
>     2. Then you need to read this file encoding it to base64 and storing this string into a variable (both libraries cited have the methods to do this). Here you need to be careful with memory management - I was storing this _huge_ string on RAM and it was breaking everything.
> 
>     3. Pass the string to Reader as `src = {{ base64: variableContainingBase64String }}`

How did you get past the memory issue regarding a huge b64 string?

**Comment by fabiancarlos** [comment]
@anacchaves exactly.. the memory issue, is just because of the base64. But you can use something like a debounce (that is like a setTimeout execute this code later) of the lodash library, to delay the render of file, and not make that this epubjs lib miss to render your ebook.

**Comment by fabiancarlos** [comment]
> > update: everything is working just fine :} I was having issues related to memory management that were unrelated to this library. For anyone wondering:
> > ```
> > 1. Once you have your file locally you need to access this file using some file management lib (RNFetchBlob, expo File System etc - any of these should have the methods you need)
> > 
> > 2. Then you need to read this file encoding it to base64 and storing this string into a variable (both libraries cited have the methods to do this). Here you need to be careful with memory management - I was storing this _huge_ string on RAM and it was breaking everything.
> > 
> > 3. Pass the string to Reader as `src = {{ base64: variableContainingBase64String }}`
> > ```
> 
> How did you get past the memory issue regarding a huge b64 string?

@csmattila delay to render the ebook, based the size of your file (creating your logic). You could use something with setTimeout, or debounce(loadsh), but basically, delay execution of rendering the component, to assign the base64 variable reference to the lib epub.

**Comment by DanielReezende** [comment]
@fabiancarlos, 

> > > atualização: tudo está funcionando bem :} Eu estava tendo problemas relacionados ao gerenciamento de memória que não estavam relacionados a esta biblioteca. Para quem está se perguntando:
> > > ```
> > > 1. Once you have your file locally you need to access this file using some file management lib (RNFetchBlob, expo File System etc - any of these should have the methods you need)
> > > 
> > > 2. Then you need to read this file encoding it to base64 and storing this string into a variable (both libraries cited have the methods to do this). Here you need to be careful with memory management - I was storing this _huge_ string on RAM and it was breaking everything.
> > > 
> > > 3. Pass the string to Reader as `src = {{ base64: variableContainingBase64String }}`
> > > ```
> > 
> > 
> > Como você superou o problema de memória em relação a uma enorme string b64?
> 
> @csmattilaatraso para renderizar o ebook, baseado no tamanho do seu arquivo (criando sua lógica). Você poderia usar algo com setTimeout, ou debounce(loadsh), mas basicamente, atrasar a execução da renderização do componente, para atribuir a referência da variável base64 à lib epub.


Good afternoon my friend, do you have an example of how to create this delay in rendering?

**Comment by timotech** [comment]
> i was able to open the example . but couldnt load a local file . how can i do that ?

Hi @eyalgromzin. How did you get the sample to open? Mine is just blank on both expo and RN app.
Probably I can see a sample or something.
Thanks

**Comment by fkazemi5236** [comment]
My problem is with the epub file. It does not recognize the file that is in the form of uri and with the .epub

**Comment by victorsoares96** [comment]
hi everyone, i solving this issue in next version and added some examples in this repository, sorry for answering so late..
