### ISSUE TITLE
How do I make changeFontSize and changeFontFamily methods work?

### ISSUE THREAD

**Issue by SamuelPremji** [victorsoares96/epubjs-react-native#80]
The issue seem to be with the library but I have no idea what causes the issue and I've been trying to fix it for weeks.

**Comment by Anton-Kravkenko** [comment]
you need to wrap all component where you using a hook in ReaderProvider

**Comment by SamuelPremji** [comment]
> you need to wrap all component where you using a hook in ReaderProvider

Can you give an example? Like isn't this supposed to work: 

export default function App() {
  const { width, height } = useWindowDimensions();
  const {changeFontSize} = useReader();

  return (
    <SafeAreaView>
      <ReaderProvider>
        <Reader
          src="https://s3.amazonaws.com/moby-dick/OPS/package.opf"
          width={width}
          height={height}
          fileSystem={useFileSystem}
          onPress={() => changeFontSize('66px')}
        />
      </ReaderProvider>
    </SafeAreaView>
  );
}

**Comment by oaidinh98** [comment]
const App = () => {
    return (
        <ReaderProvider >
            <ViewEpubScreen />
        </ReaderProvider>
    )
}

const ViewEpubScreen = () => {
   // You can use useReader() here
  const {changeFontSize} = useReader();

  return (
     <Reader />
  )
}

i hope it can help you

**Comment by SamuelPremji** [comment]
> `const App = () => { return ( <ReaderProvider > <ViewEpubScreen /> </ReaderProvider> ) }`
> 
> const ViewEpubScreen = () => { // You can use useReader() here const {changeFontSize} = useReader();
> 
> return ( `<Reader />` ) }
> 
> i hope it can help you

That's what I did but it does not work.
