### ISSUE TITLE
Hooks don't seem to be working

### ISSUE THREAD

**Issue by natesanyo** [victorsoares96/epubjs-react-native#9]
Hi Victor, 

In my sample code you can see how I am calling "goToLocation" from the useReader hook, but nothing fires. I have tested goNext as well and cannot get the hook action to fire. Is there a special configuration I need for the useReader hook to work within the ReaderProvider?

`import React, { useState, useEffect } from "react";
import {
  View,
  StyleSheet,
  useWindowDimensions,
  } from "react-native";
import { Reader, ReaderProvider, useReader } from "epubjs-react-native";

import * as FileSystem from "expo-file-system";

import ActivityIndicator from "./ActivityIndicator";
import EbookMenuBar from "./EbookMenuBar";

function EbookReader({ book }) {
  const [width, setWidth] = useState(useWindowDimensions().width);
  const [height, setHeight] = useState(useWindowDimensions().height);
  const [data64, setData64] = useState("");
  const [toc, setToc] = useState([]);
  const [showToolbar, setShowToolbar] = useState(false);
  const [activeLocation, setActiveLocation] = useState(
    "epubcfi(/6/14!/4/42/7:115)"
  );
  const [locations, setLocations] = useState([]);

  const { goToLocation, getCurrentLocation } = useReader();

  const window = useWindowDimensions();

  useEffect(() => {
    setWidth(window.width);
    setHeight(window.height);
  }, [window]);

  const epubLocalUri = FileSystem.documentDirectory + book.code + "_64_epub";

  const loadData64 = async () => {
    const result = await FileSystem.readAsStringAsync(epubLocalUri, {
      encoding: FileSystem.EncodingType.Base64,
    });
    setData64(`${result}`);
  };

  useEffect(() => {
    try {
      loadData64();
    } catch (error) {
      console.log(error);
    }
  }, []);

  return (
    <>
      <View>
        <ReaderProvider>
          {showToolbar && (
            <EbookMenuBar toc={toc} goToLocation={goToLocation} />
          )}
          {!!data64 && (
            <Reader
              src={{
                base64: data64,
              }}
              width={width}
              height={height - 160}
              renderLoadingComponent={() => (
                <ActivityIndicator visible={true} />
              )}
              onLocationsReady={setLocations}
              onNavigationLoaded={setToc}
              initialLocation={activeLocation}
              onPress={() => {
                setShowToolbar(!showToolbar);
              }}
            />
          )}
        </ReaderProvider>
      </View>
    </>
  );
}

const styles = StyleSheet.create({});

export default EbookReader;
`

**Comment by stevcooo** [comment]
I have the exact same issue, hooks return null. 

```
import { useState, useRef } from 'react';

import { SafeAreaView, useWindowDimensions } from 'react-native';
import { Reader, ReaderProvider, useReader } from 'epubjs-react-native';
import { defaultEpub, book1 } from '../../books';

export default function ReadComponent({ book, navigation }) {
    const { width, height } = useWindowDimensions();
    const viewerRef = useRef(null);
    const { changeFontSize, goToLocation, getCurrentLocation } = useReader();
    const onLocationChangeHandler = (page) => {
        console.log(JSON.stringify(viewerRef.current)); // returns null
        console.log(getCurrentLocation()); //returnus null
    };
    return (
        <SafeAreaView>
            <ReaderProvider>
                <Reader
                    forwardRef={(ref) => (this.viewerRef = ref)}
                    src={{
                        base64: defaultEpub,
                    }}
                    width={width}
                    height={height}
                    onLocationChange={onLocationChangeHandler}
                />
            </ReaderProvider>
        </SafeAreaView>
    );
}
```

**Comment by natesanyo** [comment]
I figured out the hooks issue. If you initiate a hook within a functional component called **within** the `<ReaderProvider>` then hooks will work. I will post sample code shortly.

**Comment by natesanyo** [comment]
For `useReader` hook to work, move `<ReaderProvider>` outside the component where you are calling the hook. 

`import React from "react";
import EbookReader from "../components/EbookReader";
import { ReaderProvider } from "epubjs-react-native";
import Screen from "../components/Screen";

function EbookReaderScreen({ route }) {
  const book = route.params;
  return (
    <Screen>
      <ReaderProvider>
        <EbookReader book={book} />
      </ReaderProvider>
    </Screen>
  );
}

export default EbookReaderScreen;
`
Then for `<EbookReader>` where you can call the hooks: 

`import React, { useState, useEffect } from "react";
import { View, useWindowDimensions } from "react-native";
import { Reader, useReader } from "epubjs-react-native";

import * as FileSystem from "expo-file-system";

import ActivityIndicator from "./ActivityIndicator";
import EbookMenuBar from "./EbookMenuBar";
import defaultStyles from "../config/styles";

function EbookReader({ book }) {
  const [width, setWidth] = useState(useWindowDimensions().width);
  const [height, setHeight] = useState(useWindowDimensions().height);
  const [data64, setData64] = useState("");
  const [toc, setToc] = useState([]);
  const [showToolbar, setShowToolbar] = useState(false);
  const [activeLocation, setActiveLocation] = useState();
  const [fontSize, setFontSize] = useState(defaultStyles.epubText.fontSize);

  const { goToLocation, changeFontSize, changeFontFamily } = useReader();

  const window = useWindowDimensions();

  useEffect(() => {
    setWidth(window.width);
    setHeight(window.height);
  }, [window]);

  const epubLocalUri = FileSystem.documentDirectory + book.code + "_64_epub";

  const loadData64 = async () => {
    const result = await FileSystem.readAsStringAsync(epubLocalUri, {
      encoding: FileSystem.EncodingType.Base64,
    });
    setData64(`${result}`);
  };

  useEffect(() => {
    try {
      loadData64();
    } catch (error) {
      console.log(error);
    }
  }, []);

  useEffect(() => {
    changeFontSize(fontSize + "px");
  }, [fontSize]);

  return (
    <>
      <View>
        {showToolbar && (
          <EbookMenuBar
            toc={toc}
            goToLocation={goToLocation}
            hideAction={setShowToolbar}
            setFontSize={setFontSize}
            fontSize={fontSize}
          />
        )}
        {!!data64 && (
          <>
            <Reader
              src={{
                base64: data64,
              }}
              width={width}
              height={height - 70}
              renderLoadingComponent={() => (
                <ActivityIndicator visible={true} />
              )}
              onNavigationLoaded={setToc}
              onLocationChange={setActiveLocation}
              onPress={() => {
                setShowToolbar(!showToolbar);
              }}
              onReady={() => {
                changeFontSize(fontSize + "px");
                changeFontFamily(defaultStyles.epubText.fontFamily);
              }}
            />
          </>
        )}
      </View>
    </>
  );
}

export default EbookReader;
`
